### ISSUE TITLE
Factorio-Pyanodon: Cannot calculate mod intended Moondrop production

### ISSUE THREAD

**Issue by dengamu** [factoriolab/factoriolab#1001]
You're gonna hate me for this one...

**Describe the bug**
When removing the starter recipe for Moondrop MK01 the calculator cannot find a solution.

**To Reproduce**
1. Go to '(https://factoriolab.github.io/list?z=eJwryDLWMjRVS.JTy0y21AIC4zy1opAoLS2nyjoqoXinQgOged51RKN4p5AMoI6yOtwo3sNES6u4jigY72SUTrRitTTDeL94x3infLVikLN9dLW03IG0lqOWgZaxWpk5AL8fciI_&v=7#step_0_recipes)'
2. See error

**Expected behavior**
The mod intends for this and most other Alien Life products to use a starter recipe and then input those items into the growth recipes. For Moondrop specifically, you make Moondrops, then turn them into seeds. The seeds then grow into Moondrop, which are again turned into seeds. This is a very cyclical process. 

**Screenshots**
![image](https://user-images.githubusercontent.com/62602738/219142329-41220cda-a359-48cd-990b-e1bb57263753.png)
![image](https://user-images.githubusercontent.com/62602738/219142374-0ebd22b9-581d-45df-8357-3756a2f37213.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium
 - Version 104.0.5112.114

**Additional context**
Good luck.

**Comment by dengamu** [comment]
In addition the Moondrop seed recipe shown is incorrect. From https://github.com/pyanodon/pyalienlife/blob/910bde2d1c4ce7a6cee027a9b83222609f59a131/prototypes/recipes/moondrop/recipes-moondrop.lua this is the numbers for Moondrop seeds:
![image](https://user-images.githubusercontent.com/62602738/219143651-82fa5186-a501-4e83-a11a-39787d3b79eb.png)

**Comment by dcbroad3** [comment]
The calculator being unable to find the solution is probably not a bug. The recipe being incorrect might be a bug, I'll look into it.

**Comment by dengamu** [comment]
> The calculator being unable to find the solution is probably not a bug. The recipe being incorrect might be a bug, I'll look into it.

That's correct. I understand it's intended behavior, but it also does not accurately reflect how a player would put together a factory for that item. This might tie in with #942 in order to have the starter items inserted into production.
