### ISSUE TITLE
Reduce duplicate icons

### ISSUE THREAD

**Issue by aeosynth** [factoriolab/factoriolab#1002]
The default view shows the same icon repeated 3x, in the tree, items and machines column. This seems cluttered, and wastes space. I'd like to show a single product icon per row (plus the machine icon). An icon column could be added and shown if the tree column is hidden, ensuring that one of the two is always visible.

**Comment by dcbroad3** [comment]
Well.. the machines column shows a recipe icon, which may or may not be the same as the item icon. Though I could try to hide the recipe icon if it's the same, but it's actually not totally straightforward to know up front if it has the same icon.
Could hide the item column icon if tree column is present though, that much is definitely reasonable

**Comment by aeosynth** [comment]
An additional request: move the machine column next to the tree so that the machine/recipe/product icons are all grouped together.
