### ISSUE TITLE
No Preset for AAI and Space Exploration together

### ISSUE THREAD

**Issue by JustABlueLily** [factoriolab/factoriolab#1020]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dcbroad3** [comment]
Unless I'm misunderstanding the question, Space Exploration already includes AAI. You can see the exact mods included in each data set by clicking on the "i" to the right of the dropdown in the settings field. For Space Exploration:
![image](https://user-images.githubusercontent.com/8430702/224142298-303054fe-2b29-4e14-8012-165b4bed6e46.png)

**Comment by dcbroad3** [comment]
Closing, let me know if you can provide further information about this request.
