### ISSUE TITLE
Add option to exclude proliferator production from factory tree [DSP]

### ISSUE THREAD

**Issue by curiousdannii** [factoriolab/factoriolab#1023]
I use proliferator in all my factories, and I love how Factoriolab can do all the calculations with proliferator! But the way Factoriolab works can be confusing as it includes the cost of producing proliferator in the factory report. That means that the coal required can be much higher than what is actually required for the product I am producing. And if the product shares some ingredients like energetic graphite or diamonds with proliferator then they're brought to the top rather than being nested inside the product tree.

A simple request: add a check box to exclude proliferator production from the factory. If it's selected then act like there's an infinite supply of proliferator, so that no ingredients or power need to be consumed to produce it. If it's not selected then the coal, nanotubes etc and power for producing proliferator would continue to be calculated like at present.

**Comment by dcbroad3** [comment]
If I understand your request correctly, this feature actually already exists! Try clicking on the proliferator icon in the list view, it will 'ignore' it.

![image](https://user-images.githubusercontent.com/8430702/227948018-78234771-d337-4cb3-8607-7bfd9b28df83.png)

**Comment by curiousdannii** [comment]
Oh yeah, that works great! Thanks!
