### ISSUE TITLE
Calculation In Numerical Input Boxes

### ISSUE THREAD

**Issue by DeadlyDad** [factoriolab/factoriolab#1031]
**Is your feature request related to a problem? Please describe.**
Currently, only numbers can be entered for output rate/etc., so if you want to calculate something, you have to use a separate app.

**Describe the solution you'd like**
Take a page from spreadsheets and treat any input that starts with '=' as a formula to be calculated.  (The result can be displayed in grey text on the left side of the input box.)  A simple example might be '=5 * 45' to calculate the total structures needed for 5 lines of production where each line produces 45 items per minute.  Sure, users could just enter 225, but every time they change either the number of lines or their production rates, they would have to recalculate.  ...and what if they add new, more efficient lines without replacing the old ones?   Would it not be *FAR* easier to simply change the formula to '=5 * 45 + 3 * 60'?

Cheers!
Keith

**Comment by dcbroad3** [comment]
I'll have to see if there's already a package out there that takes a string like that and solves it. If so, I'd consider using it to do this, but that's not the kind of thing I'd really want to maintain myself.

**Comment by dcbroad3** [comment]
Something like this:
https://www.npmjs.com/package/string-math

**Comment by DeadlyDad** [comment]
> Something like this:
> https://www.npmjs.com/package/string-math

That looks perfect, but I would make the slight adjustment of using an equal sign in the first position to signal that the rest of the string is a formula.
