### ISSUE TITLE
Advanced circuit recipe time is set to 0.5 sec instead of 6 sec

### ISSUE THREAD

**Issue by DanGioGames** [factoriolab/factoriolab#1040]
**Describe the bug**
Starting from version, 2.2.0 Advanced circuit recipe time (+ some other, see comment below) is set to 0.5 seconds in FactorioLab :

![image](https://github.com/factoriolab/factoriolab/assets/75941029/b7cdc9c2-af01-4afc-8f21-073218fa169a)

It should be 6 seconds : 
![image](https://github.com/factoriolab/factoriolab/assets/75941029/8dcc7501-85e8-4cd9-9373-1300667c9977)

**Comment by DanGioGames** [comment]
It seems that there's some other recipes that have been set on 0.5 seconds :
- Low density structures
- Processing units
- Batteries

**Comment by dcbroad3** [comment]
That's bizarre, thanks for calling this out, I'll look into it asap
