### ISSUE TITLE
How to limit on machine count?

### ISSUE THREAD

**Issue by adamburgess** [factoriolab/factoriolab#1044]
**Describe the bug**
I used to be able to choose machines in this dropdown:

![image](https://github.com/factoriolab/factoriolab/assets/7473960/bd6ee7ad-6609-4a18-a20a-b75f843cbb6d)

Now I can't. Has it been moved somewhere else?

**To Reproduce**
add item, open dropdown, no machines listed.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome 113
 - Version 2.2.1

**Additional context**
also now green chips for space exploration has the icon of the wood recipe which is annoying :P

**Comment by adamburgess** [comment]
![image](https://github.com/factoriolab/factoriolab/assets/7473960/0146ce77-28a2-4deb-bf22-7341532cf328)

Maybe this input could be improved to make it more obvious that it controls the amount of machines without hovering?

**Comment by dcbroad3** [comment]
As far as the incorrect icon, I'll look into it. 
And I agree with that, I'll think about it. I thought about just calling it machine objectives instead of recipe objective to be honest.

**Comment by dcbroad3** [comment]
Icons should be fixed, I'm going to leave this issue open as a request to improve the UX for objectives by machine count.
