### ISSUE TITLE
Probabilistic recipes seem to be missing

### ISSUE THREAD

**Issue by agmlego** [factoriolab/factoriolab#1058]
Working with the Space Exploration modpack on the calculator, I noticed that probabilistic recipes, such as most of the uranium fuel cell chain, are just...missing.

![image](https://github.com/factoriolab/factoriolab/assets/61333/46973748-8ea7-4712-963f-3c3063e77533)

**Comment by dcbroad3** [comment]
I found a couple bugs in the new data generator that may be related, I just haven't finished rebuilding all the data sets with the fixed generator. Hopefully this is already fixed in that branch but I'll check, and fix this as well if not.
