### ISSUE TITLE
The calculator does not import active/inactive recipes from older links

### ISSUE THREAD

**Issue by socks-the-fox** [factoriolab/factoriolab#1062]
**Describe the bug**
The Satisfactory calculator does not import active/inactive recipes from older links. I had curated the recipes to fit within the limits imposed by the available resources, as well as convenience, but loading the link only shows the default recipe list now.

**To Reproduce**
1. Visit an older link like [this](https://factoriolab.github.io/list?z=eJw1zsEKwjAQBNC.yWFO2ZbWek20EUUUBD0uVBBbL9Wq-PnutBrYl4VMku03kExjgngN-9E42kKATLeQ3GtcQyrvgdw1R9eGK0RDbqysbhD3KABEu1BYeG59mPrSziuGa5LIjpxIT-7kY8QFOZCO8DQO5EleBhP179fG6mxlc2o3TaEMMmfPuQtjNhEg5cwNti.xX8m9qy9GxD5w&v=8)
2. Dismiss limit notice
3. Notice that only the default recipes are active, so some products are suboptimal, and other products aren't even calculated.

**Expected behavior**
Calculations import old active recipe list and convert to whatever new format the system uses.

**Comment by dcbroad3** [comment]
Could you clarify which recipes you are expecting to be excluded but are not being excluded? The old active recipe list should be migrated, and when I open the link you attached, I can see that some recipes are disabled.

The following recipes appear to be disabled by your link:

- crystal-oscillator
- electromagnetic-control-rod
- encased-plutonium-cell-instant
- encased-uranium-cell
- fused-modular-frame-heat
- high-speed-connector
- motor
- motor-electric
- non-fissile-uranium-fertile
- plutonium-fuel-rod-unit
- radio-control-unit-system
- silica
- stator
- steel-ingot
- steel-ingot-coke
- steel-ingot-compacted
- alumina-solution
- aluminum-casing
- aluminum-ingot
- cable
- cable-coated
- circuit-board
- circuit-board-caterium
- circuit-board-electrode
- concrete-fine
- concrete-rubber
- cooling-system-device

**Comment by dcbroad3** [comment]
Actually, the link you attached is a v8 link, which is the current version. Is it possible you copied in the link after loading it, instead of the original URL? I don't get the limit warning either.

**Comment by socks-the-fox** [comment]
My bad, here's the actual bookmark I have: https://factoriolab.github.io/list?z=eJw1ik0LgkAYhP.NHua0q.jR9X1NpYiCoI4LBpF60dTwNL-9TWhgHobhGY5wkdcKznq5bNSNLVxuLaAHf4KLrWluppUXnJc4oA7t4cw7CQoQJdbrDpBtmudPCDfg0sxMQMqcUlIqyplypwyUkbJSC-qV2lEH6kSdqQsLlqzZ8MGWHXvOXLhij38q88m-5UI11g__&v=7

For me it's only showing the default recipes on loading, it won't even do any of the plutonium rod line because it doesn't have some of the recipes it needs.

![image](https://github.com/factoriolab/factoriolab/assets/10619770/325dc7b7-6852-4e52-a222-f9ffd75117d1)

![image](https://github.com/factoriolab/factoriolab/assets/10619770/eeac6dcc-241c-43ec-bfc5-34486871fb37)

I have done a forced reload in my browser.

**Comment by socks-the-fox** [comment]
Looking at the recipe list I screenshot, it's not even a "default recipe list," as some of the basic recipes are disabled as well (cable, motors, the default uranium, crystal oscillators, control rods). Did alt recipe naming get changed between versions? It looks like it disabled all the non-default alt recipes, then disabled all the basic recipes I had deselected.

**Comment by dcbroad3** [comment]
> Strange, it _consistently_ loads the recipe list in the screenshot on my computer. The only thing I can think of is that it's not recognizing that all of the other recipes _should_ be enabled, so instead of starting from "everything on" and turning off those, it's starting from "basic Satisfactory default" where a bunch of recipes are already off.

OH. OK. I see what you mean now. I'll look into it.

**Comment by dcbroad3** [comment]
Opening a PR but think I will have to spend some time fixing up tests. In the meantime you can test the fix at https://factoriolab.github.io/staging/satisfactory if you're interested (Might have to use a private browsing tab to get that URL to load)

**Comment by socks-the-fox** [comment]
Hm, [staging](https://factoriolab.github.io/staging/list?z=eJw1ik0LgkAYhP.NHua0q.jR9X1NpYiCoI4LBpF60dTwNL-9TWhgHobhGY5wkdcKznq5bNSNLVxuLaAHf4KLrWluppUXnJc4oA7t4cw7CQoQJdbrDpBtmudPCDfg0sxMQMqcUlIqyplypwyUkbJSC-qV2lEH6kSdqQsLlqzZ8MGWHXvOXLhij38q88m-5UI11g__&v=7) still has the same results. The staging version still shows `2.2.4 (staging)`, but if I refresh it changes to `2.2.5 (staging)` though by then it has already gone through the 2.2.4 process and updated the URL so it's stuck with the wrong list.

**Comment by dcbroad3** [comment]
If you try it again it should work.. it just didn't load the latest version the first time you opened it in that browser. I just tried a second time and it worked I believe.
