### ISSUE TITLE
Jerry can fuel selection

### ISSUE THREAD

**Issue by dengamu** [factoriolab/factoriolab#1067]
**Is your feature request related to a problem? Please describe.**
With the addition of alternative fuel types added in Py (e.g. Jerry cans), these are available in many different forms. The calculator has a preferred fuel type selection for solid fuels. This same feature is not available for the jerry cans.  A certain fuel type is automatically assumed. All Jerry cans offer the same fuel rating so production efficiency is the main concern for mass use, however, this also means that locally produced excess liquid might be preferred for certain machines.

**Describe the solution you'd like**
Selection capability for Jerry cans, preferably per machine/recipe. 

**Describe alternatives you've considered**
Excluding fill recipes. This is not entirely feasible because of the last sentence in the above paragraph.

**Additional context**
I have checked and at my current stage there are no production machines that accept both types of fuels. Just cars which are irrelevant to this issue.

**Comment by dcbroad3** [comment]
I think this is already covered by #657
