### ISSUE TITLE
[Feature Request] Factorio: Support for unordinary beacons setup

### ISSUE THREAD

**Issue by USSX-Hares** [factoriolab/factoriolab#1086]
### Is your feature request related to a problem? Please describe.
Hi there. When using the green efficency modules, their bonus can't exceed the threshhold value of -80%, regardless of how many of them you use. However, they can be used to compensate the power usage penalty of blue speed or red producivity modules.

<details>
<summary>Click here to expand</summary>

Here are the calculations for the Assembler 3, with all tier 3 modules, surrounded with the fully-equipped 12 beacons.
The goal of these calculations is to maximaze speed and producivity while capping the energy consumption (and thus pollution) at -80%.
The numbers are for the *effective ammount of modules*, meaning 1 per machine slot and 0.5 per beacon slot.

#### Max producivity:
 * 4x Prod 3
 * 1.5x Speed 3
 * 10.5x Green 3

#### Max speed:
 * 0x Prod 3
 * 6x Speed 3
 * 10x Green 3

Spreadsheet where I calculated all these values:
https://docs.google.com/spreadsheets/d/1i5VhFCT5ECAUoL1AC-fVCqyclcLVzuI1o5zNBJ5gmdk/edit#gid=0

</details>

As you can see above, on both setups the different beacons have the differnt modules inside, and thus it's impossible to input them to the FactorioLab.

### Describe the solution you'd like
Add a submenu for the beacons column wich would allow selecting more than one beacon configuration per machine.

### Describe alternatives you've considered
By now, you can input the number of beacons filled with non-green modules and be fine, it will generate the correct values for the items per second.
However, by doing so you completely ruin the calculations for the energy consumption and for the pollution generation, which are crucial for the "green play".

### Additional context
May be similar to #513, but this also requires an ability to have an option to select the same beacon prototype more than once (and fill them with the different modules).

**Comment by dcbroad3** [comment]
Is this what you're requesting?
![image](https://github.com/factoriolab/factoriolab/assets/8430702/e9954e1d-9184-436a-ac3a-c61c1e2a819a)

**Comment by USSX-Hares** [comment]
Yeah, something like that.

**Comment by USSX-Hares** [comment]
Wait. Last time I checked, there were no such feature...

**Comment by USSX-Hares** [comment]
@dcbroad3 is there any option to set these as defaults on the settings panel?

**Comment by dcbroad3** [comment]
No way to set preferences like that in the settings panel, no. 
When you select multiple modules per beacon, it does only pick one of them. The intent is only to set a fallback; e.g. if you wanted to set productivity module as your first preference and speed modules as a fallback for recipes that don't allow productivity modules. There is currently no way to actually set individual module preferences on machines or beacons from the settings menu.

Here's a related feature request:
https://github.com/factoriolab/factoriolab/issues/388
