### ISSUE TITLE
Technology is not filtered to only labs that can research it

### ISSUE THREAD

**Issue by adamburgess** [factoriolab/factoriolab#1089]
**Describe the bug**
In Space Exploration, any research that contains space packs must be done using the space lab, but factoriolab allows burner/electric lab

**To Reproduce**
1. use space exploration
2. add any technology that requires space packs, e.g. rocket survivability 4
3. the machines include burner and electric lab

**Expected behavior**
machine only includes space lab

**Screenshots**
![image](https://github.com/factoriolab/factoriolab/assets/7473960/1a3e00af-5f70-4323-9e55-d7048996505c)
![image](https://github.com/factoriolab/factoriolab/assets/7473960/03263f8e-cbfd-4c3a-a421-371bb8a39590)

allows all 3:
![image](https://github.com/factoriolab/factoriolab/assets/7473960/b0b23d01-020a-4f28-a635-666bf2f80b97)

**Additional context**
Tis a data problem, the data.json lists the burner and electric lab as producers for those items.
```json
{
    "id": "se-rocket-survivability-4",
    "name": "Rocket survivability",
    "category": "technology",
    "row": 0,
    "time": 60,
    "producers": [
        "burner-lab",
        "lab",
        "se-space-science-lab"
    ],
    "in": {
        "automation-science-pack": 1,
        "logistic-science-pack": 1,
        "chemical-science-pack": 1,
        "utility-science-pack": 1,
        "se-astronomic-science-pack-1": 1,
        "se-rocket-science-pack": 1,
        "space-science-pack": 1
    },
    "out": {
        "se-rocket-survivability-4": 1
    },
    "technology": {
        "prerequisites": [
            "se-rocket-survivability-3"
        ]
    },
    "icon": "se-rocket-survivability-1",
    "iconText": "4"
}
```

btw I love your tool, and the data.json is great, I'm making a tool that can find the optimal amount of speed modules to reach an integer machine count and it's great to be able to support any mod that factoriolab supports :)

**Comment by dcbroad3** [comment]
Thanks for the report, I'll have to see if I can figure out how those are filtered in the raw prototype data ... This might be relatively easy to fix
