### ISSUE TITLE
Missing Research links for Single-use ATMOS science in SeaBlock

### ISSUE THREAD

**Issue by falconraptor** [factoriolab/factoriolab#1099]
**Describe the bug**
Missing research links for the ingredients of "Single-use ATMOS" science in Factorio SeaBlock.

**To Reproduce**
1. https://factoriolab.github.io/
2. select Factorio Sea Block
3. Add "Single-use ATMOS set" (lime green science) from the "Science Stuff" tab
4. Observe calculations are missing for the ingredients "ATMOS Instrumentation" and "ATMOS Reaction Nodes"
  - The "Unlocked by" research icon is broken, leads me to believe those items were tied to an invalid research

**Expected behavior**
You can see the whole tree for these items, including the smelting of the ingots.

**Screenshots**
![image](https://github.com/factoriolab/factoriolab/assets/7518797/b80675b5-d76b-46d7-855b-d9a5eef0fdc1)

**Desktop (please complete the following information):**
 - OS: Windows 10 v22H2 (Build 19045.3086)
 - Browser: Chrome v114.0.5735.133
 - FactorioLab: 2.3.11

**Comment by dcbroad3** [comment]
Probably related to #1098, I do think there's something wrong with the sea block data. This will be next on my list.
