### ISSUE TITLE
reorder saved states

### ISSUE THREAD

**Issue by aeosynth** [factoriolab/factoriolab#1111]
I want to organize my saved states into an ordered progression. It's not possible to do this at all currently, because it seems that deleting a state and then saving a new state with the same name will use the old position.

**Comment by dcbroad3** [comment]
I am updating the code to sort these alphabetically, so if you want them to be sorted non-alphabetically, you can prefix them with a number or an order indicator. I think a full implementation of manual re-ordering would likely be overkill here.

**Comment by aeosynth** [comment]
good enough, thanks!
