### ISSUE TITLE
[Dyson Sphere Program] No hint with recipe for accumulator

### ISSUE THREAD

**Issue by jack128** [factoriolab/factoriolab#1120]
**Describe the bug**
In "Select An item"  dialog, when I hover on a item, popup a hint with recipe. But for accumulator there is no recipe in hint.

**Expected behavior**
I'd like get a hint with recipe

**Screenshots**
There is recipe in hint for Tesla tower
![image](https://github.com/factoriolab/factoriolab/assets/883874/8f1f01e6-7821-49ce-8998-479088f752ef)
No recipe for accumulator
![image](https://github.com/factoriolab/factoriolab/assets/883874/81125fca-bb07-41b9-97f9-999aad86c54b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - 115.0.5790.171

**Comment by dcbroad3** [comment]
This occurs because there are two recipes for accumulators; one to manufacture them, and one from discharging the energy from a full accumulator. There should be other items like hydrogen that also don't show a recipe in the tooltip for the same reason.
