### ISSUE TITLE
Seemingly infinite loop calculating space exploration dependencies

### ISSUE THREAD

**Issue by alexcrichton** [factoriolab/factoriolab#1175]
**Describe the bug**
JS seems to infinitely loop (or probably just executes for a really really long time) when an output of "Broad astronomic catalogue" is added in the space exploration expansion.

**To Reproduce**

1. Go to https://factoriolab.github.io/?s=sxp&v=9
2. Click on "Add items"
3. Search for "Broad astronomic"
4. Click on the blue cube looking thing
5. Browser should give a warning about the page consuming resources, and everything locks up

**Additional context**
This worked a day or so ago so, ironically right around the time that we started looking into planning out our factory for this stage of space exploration! This provided a great opportunity for bisection and locally a bisection pointed at https://github.com/factoriolab/factoriolab/pull/1165. Before that commit the dependency calculation terminates, but afterwards (which I presume is what's currently deployed) it infinite loops.

**Comment by alexcrichton** [comment]
Oh I also wanted to highlight that this tool has been extremely useful and it's very well done, my friend and I are absolutely loving using it! Thank you so much for working on it!

**Comment by dcbroad3** [comment]
Oh no. Just wrote a new algorithm to sort steps but looks like you've found an edge case that causes it to hang. I'll look into this asap.

**Comment by dcbroad3** [comment]
New sorting algorithm was reverted, I'm working on a replacement that does not hang.
