### ISSUE TITLE
Sea Block recipe prerequisites missing from data

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factoriolab#1180]
Cannot produce sacrificial electromagnets in Sea Block, the recipe indicates a prerequisite that appears to be missing from the data set.

Reported by Oleg in Discord

**Comment by eterevsky** [comment]
Screenshots for the context:

![image](https://github.com/factoriolab/factoriolab/assets/2182541/3eba1984-5b04-4f1a-ad57-73cff6193c99)

![image](https://github.com/factoriolab/factoriolab/assets/2182541/b08a3e7f-9a9f-4ee4-a017-96587eec0415)

**Comment by eterevsky** [comment]
There are other items that similarly can't be produced. For example for green science the recipe for the science pack itself is found, but not for its precursors: 

<img width="915" alt="image" src="https://github.com/factoriolab/factoriolab/assets/2182541/19a216be-f6b7-4d75-bce8-030afd181acd">

**Comment by eterevsky** [comment]
Thank you! I've checked the fix on staging and it seems to work. However, the technologies for the research packs now appear in the list of technologies twice and you need to have both of them to have a correct plan.
