### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by mani00132** [factoriolab/factoriolab#1214]
Hey there

First of all, Thank you soo much for this awesome tool! This is such an awesome possibility to plan your factory.

I gave it a go and made a German translation file for you. I hope that helps to further improve FactorioLab. 

Looking forward to getting an answer/integration or similar :D 

It seems as if github doesnt like json files as attachments so ill post it here... (filename would be "de.json")

`{
  "cancel": "Abbrechen",
  "ok": "OK",
  "yes": "Ja",
  "reset": "Zurücksetzen",
  "none": "Keine Resultate",
  "app": {
    "factory": "Fabrik",
    "list": "Listenansicht",
    "flow": "Flow-Ansicht",
    "data": "Daten",
    "error": "Fehler",
    "errorDetail": "Die Applikation meldet einen Fehler:",
    "resetTooltip": "Zum Zurücksetzen klicken",
    "simplexSolved": "Simplex {{ resultType }}: {{ time }}ms, Kosten: {{ cost }}",
    "simplexUnsolved": "Simplex {{ resultType }}",
    "migrationWarning": "Warnung Migration"
  },
  "options": {
    "column": {
      "checkbox": "Checkbox",
      "tree": "Baum",
      "items": "Items",
      "belts": "Förderbänder",
      "wagons": "Wagons",
      "machines": "Maschinen",
      "beacons": "Effektverteiler",
      "power": "Strom",
      "pollution": "Umweltverschmutzung",
      "link": "Link"
    },
    "displayRate": {
      "perSecond": "Teile pro Sekunde",
      "perSecondSuffix": "/s",
      "perMinute": "Teile pro Minute",
      "perMinuteSuffix": "/min",
      "perHour": "Teile pro Stunde",
      "perHourSuffix": "/h"
    },
    "game": {
      "factorio": "Factorio",
      "dysonSphereProgram": "Dyson Sphere Program",
      "satisfactory": "Satisfactory",
      "captainOfIndustry": "Captain of Industry"
    },
    "inserterCapacity": {
      "capacity0": "Kein Kapazitätsbonus",
      "capacity2": "Kapazitätsbonus 2",
      "capacity7": "Kapazitätsbonus 7"
    },
    "inserterTarget": {
      "chest": "Kiste",
      "expressTransportBelt": "Expressförderband",
      "fastTransportBelt": "Schnelles Förderband",
      "transportBelt": "Förderband"
    },
    "maximizeType": {
      "weight": "Gewicht",
      "ratio": "Verhältnis"
    },
    "objectiveType": {
      "output": "Ausgang",
      "input": "Eingang",
      "maximize": "Maximiere",
      "limit": "Limit"
    },
    "preset": {
      "minimum": "Minimum",
      "modules": "Module",
      "beacon8": "8 Effektverteiler",
      "beacon12": "12 Effektverteiler",
      "upgraded": "mit Upgrade",
      "proliferated": "Vermehrt"
    },
    "objectiveUnit": {
      "itemsPerSecond": "Items/s",
      "itemsPerMinute": "Items/min",
      "itemsPerHour": "Items/h",
      "belts": "Förderbänder",
      "wagonsPerSecond": "Wagons/s",
      "wagonsPerMinute": "Wagons/min",
      "wagonsPerHour": "Wagons/h",
      "machines": "Maschinen",
      "pollutionPerSecond": "Umweltverschmutzung/s",
      "pollutionPerMinute": "Umweltverschmutzung/min",
      "pollutionPerHour": "Umweltverschmutzung/h"
    },
    "researchSpeed": {
      "speed0": "Kein Forschungsbonus",
      "speed1": "Forschungsgeschwindigkeit 1",
      "speed2": "Forschungsgeschwindigkeit 2",
      "speed3": "Forschungsgeschwindigkeit 3",
      "speed4": "Forschungsgeschwindigkeit 4",
      "speed5": "Forschungsgeschwindigkeit 5",
      "speed6": "Forschungsgeschwindigkeit 6"
    },
    "stepDetailTab": {
      "item": "Item",
      "recipe": "Rezept",
      "machine": "Maschine",
      "recipes": "Rezepte"
    },
    "theme": { "light": "Hell", "dark": "Dunkel (Standard)", "black": "Schwarz" }
  },
  "tooltip": {
    "belt": "{{ name }}\n<small><table class=\"w-100\"><tr><td>Speed</td><td>{{ speed }}{{ suffix }}</td></tr></table></small>",
    "pipe": "{{ name }}\n<small><table class=\"w-100\"><tr><td>Flow rate</td><td>{{ speed }}{{ suffix }}</td></tr></table></small>",
    "cargoWagon": "{{ name }}\n<small><table class=\"w-100\"><tr><td>Inventory</td><td>{{ size }} stacks</td></tr></table></small>",
    "fluidWagon": "{{ name }}\n<small><table class=\"w-100\"><tr><td>Capacity</td><td>{{ size }}</td></tr></table></small>",
    "fuel": "{{ name }}\n<small><table class=\"w-100\"><tr><td>Category</td><td>{{ category }}</td></tr><tr><td>Value</td><td>{{ value }} MJ</td></tr></table></small>"
  },
  "columns": {
    "header": "Spalteneinstellungen",
    "visibility": "Sichtbarkeit",
    "decimals": "Dezimalstellen",
    "fractions": "Brüche",
    "example": "Beispiel",
    "notApplicable": "N/A"
  },
  "costs": {
    "header": "Einstellungen für Kostenberechnung",
    "recipeTooltip": "Multipliziert Rezeptkosten mit definierten Kosten, normalerweise Bergbau",
    "recipe": "Rezept",
    "machineTooltip": "Multipliziert Kosten von physischen Maschinen, die Rezepte ausführen",
    "machine": "Maschine",
    "unproduceableTooltip": "Kosten von Items, die nicht mit den inkludierten Rezepten hergestellt werden können",
    "unproduceable": "Nicht produzierbar",
    "excludedTooltip": "Kosten von Items, die explizit exkludiert wurden",
    "excluded": "Exkludiert",
    "surplusTooltip": "Kosten, um Itemüberschuss zu produzieren",
    "surplus": "Überschuss",
    "maximizeTooltip": "Kosten von Maximierungsziel (muss negativ sein)",
    "maximize": "Maximieren"
  },
  "picker": {
    "includeAll": "Inkludiere alle"
  },
  "techPicker": {
    "header": "Wähle erforschte Technologien",
    "unlockAll": "Alle freischalten",
    "showLabels": "Zeige Namen",
    "import": "Importiere",
    "importTooltip": "Importiere eine Liste von mit Komma getrennten Technologie-IDs von deinem Spiel",
    "importHeader": "Importiere erforschte Technologien",
    "importInstructions": "Wähle eine Liste von mit Komma getrennten Technologie-IDs von deinem Spiel",
    "available": "Verfügbar",
    "locked": "Gesperrt",
    "researched": "Erforscht"
  },
  "landing": {
    "welcome": "Willkommen bei <b>FactorioLab</b>! Lass uns starten.",
    "addItems": "Items hinzufügen",
    "addMachines": "Maschinen hinzufügen",
    "selectAnItem": "Wähle ein Item",
    "selectARecipe": "Wähle eine Rezept",
    "loadSavedState": "Lade eine Speicherung",
    "loadLastState": "Lade letzte Speicherung",
    "help": "Hilfe, um loszulegen",
    "skip": "Überspringen",
    "bypass": "Zeige diese Meldung in Zukunft nicht wieder"
  },
  "wizard": {
    "back": "Zurück",
    "objectiveType": "Was ist dein Ziel?",
    "produceItems": "Ich möchte Items oder Forschung produzieren",
    "produceItemsButton": "Wähle ein Item",
    "runMachines": "Ich möchte eine Anzahl Maschinen laufen lassen",
    "runMachinesButton": "Wähle ein Rezept",
    "itemObjectiveItems": "Wie viel möchtest du produzieren?",
    "recipeObjectiveMachines": "Wie viele Maschinen möchtest du laufen lassen?"
  },
  "settings": {
    "header": "Einstellungen",
    "reset": "Alle Einstellungen zurücksetzen",
    "resetWarning": "Diese Aktion wird alle gespeicherten FactorioLab-Einstellungen in diesem Browser löschen, bist du sicher, dass du fortfahren willst?",
    "savedStates": "Speicherungen",
    "createSavedState": "Erstellen",
    "editSavedState": "Umbenennen",
    "deleteSavedState": "Löschen",
    "saveSavedState": "Speichern",
    "selectSavedState": "Wähle Speicherung",
    "nameSavedState": "Namen eingeben",
    "saveState": "Speichere Speicherung",
    "requestMod": "Anfrage für Mod stellen",
    "game": "Spiel",
    "gameTooltip": "Wähle, welchen Rechner verwendet werden soll, oder benutze die links in der Titelleiste",
    "modSet": "Mod gesetzt",
    "modSetTooltip": "Wähle deine Version von Factorio oder die gewünschten Mods",
    "modVersions": "Versionen",
    "mod": "Mod",
    "version": "Version",
    "techsResearched": "{{ count }} Technologien erforscht",
    "allTechsResearched": "Alle Technologien wurden erforscht",
    "techsTooltip": "Klicke, um die erforschten Technologien zu ändern. Gesperrte Rezepte werden in der Berechnung nicht genutzt werden.",
    "itemsExcluded": "{{ count }} Items exkludiert",
    "itemsTooltip": "Klicke, um die inkludierten Items zu ändern. Exkludierte Items werden in der Lösung nicht produziert werden.",
    "itemsHeader": "Wähle inkludierte Items",
    "recipesExcluded": "{{ count }} Rezepte exkludiert",
    "recipesTooltip": "Klicke, um die inkludierten Rezepte zu ändern. Exkludierte Rezepte werden nicht in der Berechnung benutzt werden.",
    "recipesHeader": "Wähle inkludierte Rezepte",
    "factory": "Fabrik",
    "preset": "Voreinstellung",
    "presetTooltip": "Wähle eine Standard-Voreinstellung für Maschineneinstellungen",
    "addMachineTooltip": "Maschinenpräferenz hinzufügen",
    "removeMachinePreference": "Maschinenpräferenz entfernen",
    "machineDefaults": "Maschinenstandards",
    "machineTooltip": "Wähle Maschinenpräferenz",
    "fuelTooltip": "Wähle Brennstoff",
    "modifierTooltip": "Wähle Modifier",
    "overclockTooltip": "Wähle Übertaktung in Prozent",
    "beaconCountTooltip": "Wähle Anzahl von Effektverteilern",
    "beaconTooltip": "Wähle Effektverteilerpräferenz",
    "beaconModuleTooltip": "Wähle Effektverteilermodul",
    "moveMachinePreference": "Verschiebe Maschinenpräferenz",
    "moveUp": "Nach oben verschieben",
    "moveDown": "Nach unten verschieben",
    "estimateBeaconPowerUsage": "Schätze Strombedarf von Effektverteilern",
    "estimateBeaconPowerUsageTooltip": "Aktiviere, um den Strombedarf der Effektverteiler anhand von einer geschätzten Durchschnittsanzahl von Effektempfänger pro Effektverteiler zu schätzen",
    "averageBeaconReceivers": "Durchschnittliche Anzahl an Effektempfänger",
    "averageBeaconReceiversTooltip": "Durchschnittliche Anzahl an Maschinen, die von jedem Effektverteiler beeinflusst werden; Das Minimum beträgt 1",
    "proliferatorSelfSpray": "Proliferator Selbstbesprühung",
    "proliferatorSelfSprayTooltip": "Wähle den Proliferatorspray, welcher auf den Proliferator selbst angewendet wurde",
    "defaultTransportBelt": "Standard-Förderband",
    "defaultTransportBeltTooltip": "Wähle das Standard-Förderband, welches für alle Items genutzt werden soll",
    "defaultPipe": "Standard-Leitung",
    "defaultPipeTooltip": "Wähle die Standard-Leitung, die für alle Flüssigkeiten genutzt werden soll",
    "defaultCargoWagon": "Standard-Güterwagon",
    "defaultCargoWagonTooltip": "Wähle den Standard-Güterwagon, der für alle Items genutzt werden soll",
    "defaultFluidWagon": "Standard-Tankwagon",
    "defaultFluidWagonTooltip": "Wähle den Standard-Tankwagon, der für alle Flüssigkeiten genutzt werden soll",
    "fuelRank": "Bevorzugte Brenn-/Treibstoffe",
    "fuelRankTooltip": "Wähle die Reihenfolge von bevorzugten Brenn-/Treibstoffen, die überall, wo es möglich ist, genutzt werden sollen",
    "flowRateUnit": "u/sek",
    "pipeFlowRate": "Rohrdurchfluss",
    "pipeFlowRateTooltip": "Rohrdurchfluss eingeben",
    "inserterTarget": "Greifarmziel",
    "inserterTargetTooltip": "Wähle Greifarmziel",
    "bonuses": "Boni",
    "miningProductivityTooltip": "Wähle den aktuellen Produktivitätsbonus von Erzförderern in Prozent; Standard ist 0%",
    "miningProductivity": "Produktivität von Erzförderern",
    "researchSpeed": "Forschungsgeschwindigkeit",
    "researchSpeedTooltip": "Das aktuelle Level des Forschungsgeschwindigkeitsbonus eingeben; Dies beeinflusst nur die Forschung",
    "inserterCapacity": "Greifarmkapazität",
    "inserterCapacityTooltip": "Das aktuelle Level des Greifarmkapazitätsbonus eingeben; Diese Einstellung beeinflusst nur Greifarmschätzungen",
    "miningSpeed": "Geschwindigkeit von Erzförderern",
    "miningSpeedTooltip": "Die aktuelle Geschwindigkeit von Erzförderern mit Bonus eingeben; Standard ist 100%",
    "display": "Anzeige/Grafik",
    "openColumnSettings": "Öffne Spalteneinstellungen",
    "displayRate": "Einheiten für Raten",
    "displayRateTooltip": "Wähle die Zeiteinheit, die in Ratenangaben genutzt werden soll",
    "powerUnit": "Stromeinheiten",
    "powerUnitTooltip": "Wähle die Einheiten für die Stromspalte",
    "helpTranslate": "Beim Übersetzen mithelfen",
    "language": "Sprache",
    "languageTooltip": "Sprache wählen",
    "theme": "Thema",
    "themeTooltip": "Wähle Thema",
    "advanced": "Erweiterte Einstellungen",
    "maximizeType": "Typ von Maximierungswert",
    "maximizeTypeTooltip": "Wähle den Typ von Maximierungswert",
    "openCosts": "Öffne Einstellungen zu Kosten",
    "bypassLanding": "Startseite immer überspringen",
    "hideDuplicateIcons": "Verstecke doppelte Icons",
    "netProductionOnly": "Nur Nettoproduktion",
    "netProductionOnlyTooltip": "Wenn aktiviert, werden Rezepte, die das gleiche Item sowohl produzieren als auch verbrauchen, auf die Nettoproduktion reduziert.",
    "surplusMachinesOutput": "Maschinenausgabe als Überschuss",
    "surplusMachinesOutputTooltip": "Wenn aktiviert, wird der Output von Maschinenzielen als Überschuss anstatt als benötigte Items betrachtet."
  },
  "objectives": {
    "title": "Ziele",
    "removeTooltip": "Ziel entfernen",
    "typeTooltip": "Wähle Zieltyp",
    "selectAnItem": "Wähle Item",
    "selectARecipe": "Wähle Rezept",
    "valueTooltip": "Wert eingeben",
    "unitTooltip": "Einheiten wählen",
    "addItems": "Items hinzufügen",
    "addMachines": "Maschinen hinzufügen",
    "selectDisplayRate": "Wähle Anzeigerate",
    "pauseTooltip": "Berechnung pausieren/fortfahren",
    "error": "Es konnte keine Lösung gefunden werden",
    "errorDetail": "Überprüfe <b>Limit</b> und <b>Maximize</b> Ziele, sowie inkludierte Rezepte. ",
    "errorUnbounded": "Lösung ist unbegrenzt",
    "errorUnboundedDetail": "<b>Limit</b> Ziele sind möglicherweise nicht restriktiv genug für <b>Maximize</b> Ziele.",
    "errorInfeasible": "Lösung ist undurchführbar",
    "errorInfeasibleDetail": "<b>Limit</b> Ziele sind möglicherweise zu restriktiv um die <b>Output</b> Ziele zu erfüllen.",
    "errorMaximizeExcluded": "<b>Maximize</b> Ziele können nicht mit einem exkludierten Ziel verwendet werden. Wähle ein anderes Ziel oder inkludiere das aktuelle Ziel.",
    "errorNoLimits": "Keine <b>Limit</b> Ziele hinzugefügt. Füge <b>Limit</b> Ziele hinzu um das <b>Maximize</b> Ziel einzuschränken.",
    "errorSimplexInfo": "<i>Return code: {{ returnCode }}, Simplex status: {{ simplexStatus }}</i>"
  },
  "list": {
    "openColumnSettings": "Öffne Spalteneinstellungen",
    "checkedUndoTooltip": "Alle Markierungen rückgängig machen",
    "itemsUndoTooltip": "Alle exkludierten Items rückgängig machen",
    "beltsUndoTooltip": "Alle Förderbandveränderungen rückgängig machen",
    "wagonsUndoTooltip": "Alle Wagonveränderungen rückgängig machen",
    "machinesUndoTooltip": "Alle Maschinenveränderungen rückgängig machen",
    "beaconsUndoTooltip": "Alle Effektverteilerveränderungen rückgängig machen",
    "downloadTooltip": "Liste als CSV-Datei herunterladen",
    "showDetails": "Details einblenden",
    "hideDetails": "Details ausblenden",
    "overclockTooltip": "Übertaktung in Prozent",
    "beaconEachTooltip": "Effektverteiler pro Maschine",
    "beaconTotalTooltip": "Totalanzahl an Effektverteilern",
    "openNewTabTooltip": "In neuem Tab öffnen",
    "stepUndoTooltip": "Alle Veränderungen bis hierhin rückgängig machen",
    "sources": "Quellen",
    "destinations": "Zielorte",
    "depletion": "Rohstofferschöpfung",
    "inputs": "Eingänge",
    "time": "Zeit",
    "outputs": "Ausgänge",
    "inserterCountInfo": "* Greifarme werden anhand der Ziel/Kapazität Einstellungen und anhand experimentellen Daten (0.18) von <a href=\"https://wiki.factorio.com/Inserters#Inserter_Throughput\" target=\"_blank\">wiki.</a> berechnet.",
    "includedRecipes": "Inkludierte Rezepte",
    "includedRecipesInfo": "Klicke, Rezepte zu inkludieren oder exkludieren. Exkludierte Rezepte werden in der Berechnung nicht verwendet.",
    "total": "Total"
  },
  "data": {
    "notFound": "Nicht gefunden",
    "versions": "Versionen",
    "collection": "Sammlung",
    "count": "Anzahl",
    "any": "Beliebig",
    "selectedLabel": "{0} gewählt",
    "name": "Name",
    "categories": "Kategorien",
    "items": "Items",
    "beacons": "Effektverteiler",
    "beacon": "Effektverteiler",
    "belts": "Förderbänder",
    "belt": "Förderband",
    "cargoWagons": "Güterwagons",
    "cargoWagon": "Güterwagon",
    "fluidWagons": "Tankwagons",
    "fluidWagon": "Tankwagon",
    "fuels": "Brennstoffe",
    "fuel": "Brennstoff",
    "machines": "Maschinen",
    "machine": "Maschine",
    "modules": "Module",
    "module": "Modul",
    "pipes": "Leitungen",
    "recipes": "Rezepte",
    "technologies": "Technologien",
    "category": "Kategorie",
    "item": "Item",
    "recipe": "Rezept",
    "stackSize": "Stackgrösse",
    "efficiency": "Effizienz",
    "moduleSlots": "Modulplätze",
    "range": "Reichweite",
    "energySource": "Energiequelle",
    "energyConsumption": "Energieverbrauch",
    "disallowedEffects": "Unerlaubte Effekte",
    "beltSpeed": "Geschwindigkeit (Items/s)",
    "storageSize": "Lagergrösse",
    "fluidCapacity": "Flüssigkeitskapazität",
    "craftingSpeed": "Herstelltempo",
    "fuelCategories": "Brennstoffkategorien",
    "fuelCategory": "Brennstoffkategorie",
    "fuelValue": "Brennstoffwert",
    "energyDrain": "Energieabfluss",
    "pollution": "Umweltverschmutzung",
    "rocketSilo": "Raketensilo",
    "rocketPartsRequired": "benötigt Raketenbauteile",
    "rocketLaunchTime": "Zeit für Raketenstart (s)",
    "productivity": "Produktivität",
    "speed": "Geschwindigkeit",
    "sprays": "Sprays",
    "proliferator": "Proliferator",
    "burntResult": "Ergebnis nach dem Verbrennen",
    "consumedByRecipes": "Von Rezepten verbraucht",
    "producedByRecipes": "Von Rezepten hergestellt",
    "producibleRecipes": "Produzierbare Rezepte",
    "unlockedRecipes": "Entsperrte Rezepte",
    "currentPageReportTemplate": "Zeige {first} bis {last} von {totalRecords}",
    "itemSettings": "Itemeinstellungen",
    "excluded": "Exkludiert",
    "checked": "Aktiviert",
    "machineSettings": "Maschineneinstellungen",
    "moduleRank": "Modulrang",
    "beaconModuleRank": "Effektverteiler Modulrang",
    "overclock": "Übertaktung",
    "time": "Zeit (s)",
    "ingredients": "Bestandteile",
    "catalysts": "Katalysten",
    "products": "Produkte",
    "producers": "Produzenten",
    "unlockedBy": "Freigeschaltet von",
    "mining": "Erzförderung",
    "rocketPart": "Raketenbauteil",
    "technology": "Technologie",
    "prerequisites": "Bedingungen",
    "recipeSettings": "Rezepteinstellungen",
    "cost": "Kosten"
  }
}
`

**Comment by mani00132** [comment]
Well certainly its not a bug, but im not that familiar with github to change that xO

**Comment by dcbroad3** [comment]
Thanks for working on this! I'll see if I can get it added.
