### ISSUE TITLE
Hiding catalyst (looping) items in recipes crashes flow view when "hide excluded items" is checked

### ISSUE THREAD

**Issue by yiding** [factoriolab/factoriolab#1295]
**Describe the bug**
When using SE+K2, and looking at production chain for iridium, hiding cation exchange beads breaks "flow view". Doesn't seem to do it for both sankey and box diagrams. This seems to be happening after the recent sankey diagram changes.

Only happens when "Hide excluded items" is checked in the flow options. I suspect what happens is that the node for the catalyst item is removed, but because it's still a byproduct of something else that thing tries to link to the non-existent node.

**To Reproduce**

1. Go to [this](https://factoriolab.github.io/list?z=eJxdkNtu2kAURf.GDyOBYuIE.JgZZoztAQQ1TeiLBSkQqAMokOvD-vbOURupjY-8dPY-c9maY3FQSe8iWsWq4r-qvxrR0kfbRMW1PQToo-CbYBgwvgswacDoWbyzyFy6U4ALv58EPMj2RmwbkG1l9h5Q9gNy6UY34lUB66eASo60HRlciXyVzqg4elpcKpXW44FcXorbDpjPlOordVH7s1Kq5G8FY179MWT2EVpNKBEv4ZjPlRLz-cvGiSRtNgJJ30jmZid3dUOMdVz3VakStQwv5uthnSoVi4hO13RJ0W10jL5BW3SOHqFv0Uv0Gr1F79C.0A36Eb1HHzEaM8AMMbeYe8wKs8E8Yk6YNyw2wV5hu9gedoStsAvsA.aAPeNwLVwbd43r4lKcxgVzilvhtrgd7p2MrEumyfpkOdmUbEY2J7tn0GEwJW-RX5L3KFoUCUVKMaQYUYwpJhQzijNlie.gAyf4GX6F3-Nf8W98544fLPjJhi17DpzkwdW.36eKo5f0N1LlzG4_&v=9)
2. Click on "Flow"
3. See error

**Expected behavior**
Flow view does not break.

**Screenshots**

**Desktop (please complete the following information):**

Windows, Firefox

**Additional context**

Error when displaying box graph:

```
The application has encountered an error:
Error: Uncaught (in promise): Error: org.eclipse.elk.graph.json.JsonImportException: Referenced shape does not exist: i|se-vulcanite-ion-exchange-beads 1803/SB.exports<[2]</</</c.Wd@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:1222889 1803/SB.exports<[2]</</</c._d@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:1223338 hCe@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:494388 ps@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:423064 Of@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:425623 LU@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:684204 A4t@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:861645 rkt@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:861719 U4t@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:793193 ZBe@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:793240 q7t@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:1740951 1803/SB.exports<[2]</</</Gnt/e/this.dispatch@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:1741970 1803/SB.exports<[2]</</</Gnt/e/this.saveDispatch@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:1742090 1803/SB.exports<[2]</</</Gnt/t/this.postMessage/<@https://factoriolab.github.io/779.9c18f22efb29640f.js:1:1742312 8332/Lt/y</</f[0]@https://factoriolab.github.io/polyfills.1dd96880dec584a4.js:1:49203 invokeTask@https://factoriolab.github.io/polyfills.1dd96880dec584a4.js:1:28223 onInvokeTask@https://factoriolab.github.io/main.6391d6f80bfb306d.js:1:569710 invokeTask@https://factoriolab.github.io/polyfills.1dd96880dec584a4.js:1:28144 runTask@https://factoriolab.github.io/polyfills.1dd96880dec584a4.js:1:23581 invokeTask@https://factoriolab.github.io/polyfills.1dd96880dec584a4.js:1:29275 8332/o/this.invoke<@https://factoriolab.github.io/polyfills.1dd96880dec584a4.js:1:29176 8332/Lt/r/o.args[0]@https://factoriolab.github.io/polyfills.1dd96880dec584a4.js:1:48915 
```

Error when displaying sankey:
```
The application has encountered an error:
Error: missing: i|se-vulcanite-ion-exchange-beads
```

**Comment by dcbroad3** [comment]
Possibly related:
https://discord.com/channels/806885678201831424/1180202430768611461
Ensure both errors are fixed
