### ISSUE TITLE
Maximizing the byproducts handling

### ISSUE THREAD

**Issue by USSX-Hares** [factoriolab/factoriolab#1305]
Some mods add complex recipe chains which produce byproducts which must be handled properly. When desiging a sub-factory, adding too many machines to recycle them could be a very expensive overkill, and the correct number is not always obvious.

### Example
Freight Forwarding modpack adds Cobalt Processing which is a 2-stage multi-step production chain:
#### Stage One: Cobalt Ore
 * Where: Dredging Platform outposts
 * Main Product: Cobalt Ore
 * How: The Dredging Platform extractor produces 50-150 Cobalt Crust per 75s cycle, which is then processed in the Chem Plants to 40-50 Cobalt Ore, 0-8 Iron Ore, 0-8 Copper Ore, 0-4 Stone, and 0-10 Cobalt Crust; Iron and Copper are smelted to the plates, and all 4 products are packed in the Containerization machines.

![image](https://github.com/factoriolab/factoriolab/assets/29100587/d635a29b-9e35-416c-a8a4-c0bd0e8eb3f2)

#### Stage Two:
 * Where: The Mainland
 * Main Product: Cobalt Ingots
 * How: Cobalt Ore is extracted from the containers and processed in the oil refineries to Cobalt Concentrace & Tailings Water; the first is crushed via dynamite and then smelted into Cobalt Ingots, and the second is processed in 3x number of chem plants into a random ammount of Titanium Ore & Lead Ore, both of which are then smelted, randomly producing Copper Ore as a byproduct which should smelted into plates too. After that, all products should be conterized to allow shipments.

![image](https://github.com/factoriolab/factoriolab/assets/29100587/5cfebecb-39f9-49c2-a6ca-b253eaf993bb)

### The Problem
When you try to define this chain in FactorioLab, it simply does not recognize what you want. And what you want is to know how many smelting machines you need for each ore in the second recipe chain so that the system won't clock up.
I even tried setting up all of the byproducts as "output products" but the site didn't get it. The closest thing I got was marking all outputs as "x machines / Limit" and raising x until the numbers stop changing.
https://factoriolab.github.io/list?z=eJw9ij0PgkAQRP.NFpOY3EoDrScCd9cQYyw3UuAXBCOJv99dMTRv3uzOK9RgYCuhWtK3.35YMl7BziFDJv60auxXbXIdskp64neh7kZ320pZKuwv.qzYb8D0Tkk1XgydohoVKVp9WB0Mkw57lqO0EmgGsKNP8QXDrSq2&v=9#16

**Comment by dcbroad3** [comment]
This seems like something that could potentially be solved by increasing the surplus cost, and increasing the cost of recycling recipes (if you are having problems with the calculator producing a solution with too many machines to recycle as you mention).
To set the surplus cost use the "Open cost settings" button at the bottom of settings.
![image](https://github.com/factoriolab/factoriolab/assets/8430702/2b6c5c0f-5e22-436a-a8fb-1d265da33729)

To set the cost of the recycling recipes, open the data page for the recipe, and there should be a field to change (increase) its cost.
![image](https://github.com/factoriolab/factoriolab/assets/8430702/ab9382c9-9a17-49dd-9c1b-c270e366a007)

**Comment by dcbroad3** [comment]
If you still want to request this as a feature, let me know and try to provide specifics on what exactly you're requesting, because I'm still somewhat unclear.
