### ISSUE TITLE
Update Dyson Sphere program to support new recipes from Dark Fog update

### ISSUE THREAD

**Issue by hoylemd** [factoriolab/factoriolab#1308]
**Is your feature request related to a problem? Please describe.**
I'd like to use the tool to plan out production of new recipes (ammunition, turrets etc), but I can't because the recipes aren't available.

**Describe the solution you'd like**
For the new recipes to be available in the tool

**Describe alternatives you've considered**
a spreadsheet?

**Additional context**
I'm sure it's already planned, but I didn't see anything about it so I figured it couldn't hurt to ask

**Comment by GripenANM** [comment]
it is already in progress, we are currently changing how the data are being fetched. so SoonTM
