### ISSUE TITLE
DSP Dark Fog Items: Missing extra products spray, only speedup available

### ISSUE THREAD

**Issue by DanTheManOg** [factoriolab/factoriolab#1311]
**Describe the bug**
No new items for the dark fog appear to be able to procude extra products and only allow you to select speedup for the proflieration sprays.

**To Reproduce**
Select any new item from the dark fog update  and ensure you have a spray selected. Any new items In the recipe chain will also not have the extra products, even when they should.

**Expected behavior**
E.g on missile sets, you should be able to select extra products as well. I have tested in game and yes extra products option is available for all missiles and their requirements.

**Screenshots**
![image](https://github.com/factoriolab/factoriolab/assets/84956641/37e77858-34f1-408d-abac-4e60040f40e2)

**Desktop (please complete the following information):**
Windows 10, Chrome Version 120.0.6099.129 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
--

**Additional context**
--

**Comment by Velociraptor115** [comment]
Ah yeah, I forgot to update that
Will update and push in a few mins

**Comment by Velociraptor115** [comment]
@DanTheManOg 
Can you check if you are seeing the expected behaviour?
If you are satisfied, you can close the issue
