### ISSUE TITLE
DSP: Fractionation recipe ratio is broken

### ISSUE THREAD

**Issue by mrbeaver2K** [factoriolab/factoriolab#1314]
**Describe the bug**
The Deuterium Fractionation recipe is 100 hydrogen to 1 deuterium, rather than the 1% chance to convert. This breaks any recipe calculations that rely on this recipe.

**To Reproduce**

1. Go to 'Add Items'
2. Click on 'Any recipe that uses Deuterium'
3. Disable (in exclude recipes) 'the Deuterium recipe via Miniature Particle Collider and Orbital Collector'

**Expected behavior**
I expected the recipe to display the correct number of fractionators and the correct input volume.

**Desktop (please complete the following information):**

- OS: [Windows 11]
- Browser [Chrome]
- Version [2.3.81]

**Comment by mrbeaver2K** [comment]
![image](https://github.com/factoriolab/factoriolab/assets/112230379/076a2e76-e592-4f7d-a1e6-11ba78f79a7d)
Screenshot, if needed.

**Comment by Velociraptor115** [comment]
@mrbeaver2K 
Can you confirm if the recipe is working as expected now, or if there are further changes required?

**Comment by mrbeaver2K** [comment]
@Velociraptor115 
The recipe is working as intended now, thank you.
