### ISSUE TITLE
DSP: How do you fetch game data ?

### ISSUE THREAD

**Issue by Sugz** [factoriolab/factoriolab#1315]
Hi, I was just wondering you do you fetch the data for DSP ?
Any help would be welcome :)

**Comment by Velociraptor115** [comment]
Right now, I have written a mod for the game in C# which helps me dump the data I need
If you are on the DSP Modding Discord, you can find more resources there
Otherwise I'd be glad to help here

**Comment by Sugz** [comment]
If you have the C# code in a repo, I can take a look at it, thanks :)

**Comment by Velociraptor115** [comment]
I do not have the code in a repo, but let me see if I can zip it up and share

**Comment by Sugz** [comment]
Mainly the data itself. I tried using the one from factoriolab but afaik it misses a few things like the description for the items. The current data I have is outdated, but it was based on it and I just did a bunch of manual changes to the jsons. But this is rather annoying so I'd like to see if I can get everything myself.

**Comment by Velociraptor115** [comment]
[items.json](https://github.com/factoriolab/factoriolab/files/13785751/items.json)
[recipes.json](https://github.com/factoriolab/factoriolab/files/13785752/recipes.json)
[techs.json](https://github.com/factoriolab/factoriolab/files/13785753/techs.json)

This is a recent one, around version 0.10.28.20829, but not the latest. If there were any balancing changes, this won't have it. But I think there were none for dark fog items

**Comment by Velociraptor115** [comment]
If you give me a few more days, I'll clean up my data dumping mod and put it up on GitHub

**Comment by Sugz** [comment]
That looks very good thanks !. Sure take your time :)

**Comment by Velociraptor115** [comment]
@Sugz Take a look at https://github.com/Velociraptor115-DSPModding/DataDumper
It might be overkill, but I think it's generic enough for pretty much any Unity Mono game

**Comment by Velociraptor115** [comment]
[JsonDump.zip](https://github.com/factoriolab/factoriolab/files/13818200/JsonDump.zip)
Got the latest dump with the above mod
I can get all the data I wanted with just config files, so I think the mod is in quite a usable state now
Will update it with the minor issues I fixed today

**Comment by dcbroad3** [comment]
I'm going to go ahead and close this issue (since it was never really an issue in the first place).
You're welcome to continue discussion in this thread, or move the discussion to Discord which might be a better place for discussion of this kind.
