### ISSUE TITLE
The components and buildings for DSP aren't sorted in any kind of real order

### ISSUE THREAD

**Issue by Prometheus0000** [factoriolab/factoriolab#1327]
**Describe the bug**
Look at the components or buildings tabs, you can see that they're not in order. The components one is especially bad. I dunno if you originally had them in order before the DF expansion, but they're certainly not now.

It looks like they're in the correct rows from the ingame filter list (removing stuff you can't make or mine), but alphabeticalized for no reason, so please remove that and add the spaces back in.

I can accept having the drop-down on the left side being alphabetically sorted (though I think most people would prefer the upgraded buildings all in a row, regardless of what they're named), but alphabetically sorting the other two tabs is weird.

**To Reproduce**
Look at the components or buildings tabs

**Expected behavior**
To be in a reasonable order, like the one ingame

**Screenshots**
Website components
![image](https://github.com/factoriolab/factoriolab/assets/8517039/67173fa3-2b87-401e-8a10-f48832f341a9)
Ingame items
![image](https://github.com/factoriolab/factoriolab/assets/8517039/61bd547a-2950-4a71-9fa8-dcc7fdfb22f7)
Filter list image
![image](https://github.com/factoriolab/factoriolab/assets/8517039/bf849141-89cc-429e-a2b1-395c8630419a)
Website buildings
![image](https://github.com/factoriolab/factoriolab/assets/8517039/b030bd7a-0587-4bdd-a2f6-ef34acc9a050)
Ingame buildings
![image](https://github.com/factoriolab/factoriolab/assets/8517039/3e9e716c-1790-4eb9-b146-cfbe4ae8c321)

**Additional context**
This maybe should be under feature request? I wasn't sure

**Comment by Prometheus0000** [comment]
![image](https://github.com/factoriolab/factoriolab/assets/8517039/657ffef6-efb5-4fae-a4e1-10a74c884212)
Is there nothing that can be done here? I'm sure you can tell, but the shells and capsules don't line up. Does the site not allow for spaces?

**Comment by dcbroad3** [comment]
The site is designed to right align each row. You could open a request to allow gaps, but the idea is that some browsers may be narrow, causing things to wrap and then they wouldn't necessarily align anyway. 
As far as I know DSP is the only supported game that puts these gaps in..

**Comment by Prometheus0000** [comment]
Do you think it'd be worthwhile to put the plasma and shells on the second last row? Like this
![image](https://github.com/factoriolab/factoriolab/assets/8517039/fc57b11a-2fda-422a-970c-2896ad4c76f5)
Or do you think it'd be better to have it in the game's order as much as possible?
