### ISSUE TITLE
For DSP please add a way to not have proliferator production added to every build it's used in

### ISSUE THREAD

**Issue by Prometheus0000** [factoriolab/factoriolab#1328]
**Is your feature request related to a problem? Please describe.**
Every time I add proliferation to something it thinks I want to make proliferator as part of that build, which I never, ever, want to do, aside from the build *for* proliferator. So I have to go and disable the recipe again, like every day, or deal with my recipes having incorrect amounts if I don't notice.

**Describe the solution you'd like**
A default-on checkbox on the left side that specifies that the proliferator recipes will be turned off by default unless unchecked.

**Describe alternatives you've considered**
Have it save the disabled recipe setting for longer than 1 session? Though having random recipes on or off saved for longer would probably get even more annoying, and I assume it would affect all of them.

**Comment by dcbroad3** [comment]
Would it help to create a saved state with proliferator recipes disabled? Then you can start with that saved state when you open a new session, and it will load those defaults for you. 
E.G., Open this, and save the state: https://factoriolab.github.io/list?r=proliferator-1*1_proliferator-2*1_proliferator-3*1&s=dsp&v=9
Then, when you open a new session, first select that saved state, it will disable the proliferator recipes, and you can continue from there.

**Comment by Prometheus0000** [comment]
> Would it help to create a saved state with proliferator recipes disabled? Then you can start with that saved state when you open a new session, and it will load those defaults for you.
E.G., Open this, and save the state: https://factoriolab.github.io/list?r=proliferator-1*1_proliferator-2*1_proliferator-3*1&s=dsp&v=9
Then, when you open a new session, first select that saved state, it will disable the proliferator recipes, and you can continue from there.

Save the state? Like the thing in the upper left I don't know what it does and have never used? I guess that saves what changes you've made between sessions given what you've said? Honestly, I feel some parts of the website need a better explanation, like this, proliferator self-spray, preferred fuels, and the items under flow and advanced. I looked at 'support' in the upper right for support, but that was not what it was for. Is there not manual anywhere? Do I have to go to discord? I hate doing that just to look for a manual, I just end up not using features. I think some tooltips for the more complicated stuff would help if you have the time.

To be honest I was also going to make a ticket for that there should be a way to easily disable showing recipes instead of going into the dropdown and disabling the recipes (which is not convenient to do over and over), which I also did for this, but then I found out that I could click on the icon for the thing to just disable it that way. So it's easy to just do that to disable the proliferator recipes, but I do think the default should be to not have them by default be part of the build. I guess I should make a save state like you said. Do most people make their proliferator onsite because they're planning planet-sized blueprints?

**Comment by dcbroad3** [comment]
Yes, the thing in the upper left. 

Documentation would certainly do some good. At one point the project had a wiki, but eventually it was so out of date that it was no longer useful. I need to rebuild some documentation now, but I don't know when I'll get around to it. 

I don't really know what most people do, but ignoring an item by clicking its icon in the list view is hopefully a pretty easy thing to do.
