### ISSUE TITLE
Cosmetic/Usability: 'Open data page' link requires too much mouse movement precision

### ISSUE THREAD

**Issue by DRY411S** [factoriolab/factoriolab#1336]
**Describe the bug**
All pop ups have a 'Open data page' link. Whether you can click it is too 'hit and miss'.
**To Reproduce**
With factorio selected, choose any item to add to the calculator.
On any row that appears in the output, hover over every icon in the row and read the 'pop ups'
Every pop up has an 'Open data page' link,
You need to be almost 'pixel perfect' when moving the mouse from the icon into the pop up to click the link. Lack of precision causes the pop up to disappear.

**Expected behavior**

I want to be able to move to the pop up with confidence every time.

**Screenshots**

Not supplied. The issue is sensitive to motion, itself not possible to capture in a screenshot.

**Desktop (please complete the following information):**

- OS: Windows 11 Pro
- Browser: Chrome
- Version: 120.0.6099.131 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

N/A

**Additional context**
I use default default OS mouse settings. No accessibility settings, cursor shape/size etc.

**Comment by dcbroad3** [comment]
This issue is made obsolete by #1344, which removes this link in the tooltips altogether

**Comment by dcbroad3** [comment]
This issue is made obsolete by #1344, which removes this link in the tooltips altogether
