### ISSUE TITLE
Sources other than offshore pump not considered for water

### ISSUE THREAD

**Issue by dlouwers** [factoriolab/factoriolab#1339]
**Describe the bug**
Only offshore pumps are considered a possible source of water even when, for instance, only ice melting or water barrel unpacking is an option. This is particularly relevant in Space Exporation.

**To Reproduce**

1. Go to [example space science recipe](https://factoriolab.github.io/list?z=eJwr8PfSMox3dtMy0DPSArEy4CxzGMs7DcgyAbMytAxBtJMjTMTZQ8vIUN.UwAAsbaoF0qCWFKBWrAUUcVIrswQAReoWCQ__&v=9#5)
2. Click on water pump and try to change it to space factory

**Expected behavior**
I expect water to be able to come from various other sources other than an offshore pump. In the example recipe this already works frine for lubricant by specifying lubricant barrels as input.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser chrome (Brave)
- Version v1.62.156 (Jan 31, 2024)

**Comment by dcbroad3** [comment]
If you expand the row, you can open the recipes tab and specify what recipes you want to allow for water
![Screenshot_20240202-073853](https://github.com/factoriolab/factoriolab/assets/8430702/2a8db28a-6b91-4bc3-869e-6f9d33c22479)

It prefers the water pump out of the available options because it is considered cheapest.

**Comment by dlouwers** [comment]
Seems to work fine indeed. I have not been able to find any manual or tutorials on how to use these features. I am used to HellMod, but have been in games where I couldn't run that mod so this popped up as a winner. I'd be happy to write some usage instructions on the Wiki is you'd like that. Let me know.

**Comment by dcbroad3** [comment]
Yes, I definitely need to work on documentation. I'll go ahead and write up an actual issue for it.
