### ISSUE TITLE
Fractionator Power consumption is wrong

### ISSUE THREAD

**Issue by Xiraxis** [factoriolab/factoriolab#1347]
Deleted

**Comment by dcbroad3** [comment]
I'll assume by the fact the description has been changed to deleted, that this should be closed. Feel free to elaborate if this should be reopened.

**Comment by Xiraxis** [comment]
We ran into unexpected results that need further confirmation. I will open a new issue once we have at least some clarity because the fractionators behaved unpredictable. The power consumption is still wrong. But feel free to test for yourself- 
Fractionator power consumption changes with pile level of belt. And it doesn't even seem to be linear, so a 4 piled hydrogen belt will consume more than 4x the base work consumption. It is weird, and things got even weirder with different belt speeds.

**Comment by dcbroad3** [comment]
Ok, feel free to either reopen this or create a new issue if you have confirmed results. I would consider participating but I've never actually played DSP
