### ISSUE TITLE
Method to import/export unlocked recipes

### ISSUE THREAD

**Issue by ThatOhio** [factoriolab/factoriolab#1363]
**Is your feature request related to a problem? Please describe.**
I am currently doing a Nullius play-through and with the vast number of different methods / recipes available (and more importantly, not available) at certain points in my run, it is a bit tedious to adjust the chosen recipes manually.

**Describe the solution you'd like**
I'd love a method to sync my available recipes from in game with the website. Could be achieved with a simple mod that adds a button that exports your current tech level and a method to import that, likely on the recipes excluded section of the advanced menu. 

**Describe alternatives you've considered**
Technically the in game factory planners somewhat support this already, but I REALLY enjoy using this tool as it seems a bit more polished than the in game ui's are capable of. 

**Additional context**
I imagine creating this export functionality for Nullius would likely be universal regardless of mod back (assuming one of the supported packs).

**Comment by dcbroad3** [comment]
This actually exists. If you open technology settings in the calculator, there is an import button. It accepts a csv of unlocked techs. In the import dialog it can tell you two ways to generate the csv, there is a simple console script and also a mod.

**Comment by dcbroad3** [comment]
#1362 claims the console script doesn't work exactly right, but it should at least get you close for now. I'll have to test out the updated script in the pr later.

**Comment by ThatOhio** [comment]
Ahh! I can't believe I missed that feature, this is a life saver, thanks so much!
