### ISSUE TITLE
Crash when changing preset burner machine fuel

### ISSUE THREAD

**Issue by Lazula** [factoriolab/factoriolab#1372]
Attempting to change the fuel for a burner machine preset causes the program to crash.

1. Open the application and select any mod set. (tested with: 1.1.x, Sea Block, Freight Forwarding, Krastorio 2, 248k Overhaul, and Space Exploration)
2. Add a new burner machine preset or change an existing preset machine to a burner machine.
3. Change default furnace/burner miner/boiler fuel to anything else.
4. `TypeError: C is not a function`

**Screenshots**

Example: Sea Block

![image](https://github.com/factoriolab/factoriolab/assets/26179473/1f4b4f44-fdbf-4271-b7e8-51232d7cdb0e)

Selecting another fuel

![image](https://github.com/factoriolab/factoriolab/assets/26179473/b9caefc1-8023-41a8-9680-6c2cf140744f)

Crash

![image](https://github.com/factoriolab/factoriolab/assets/26179473/4b33878c-15d3-45c7-af63-b1b37c80ca8c)

**Desktop**

- OS: Linux Mint 21.2
- Browser: Firefox 122.0

**Additional context**

Running locally on current main ([31e3640](https://github.com/factoriolab/factoriolab/commit/31e3640746b5b675f9f85b4af4431860d1ed040a)) raises `TypeError: settings_r77 is not a function`.

![image](https://github.com/factoriolab/factoriolab/assets/26179473/3446991a-9bfa-40be-8e73-ea6498fd958e)

**Comment by dcbroad3** [comment]
This might be fixed in the feature branch I'm working on. If you're able to, try this out at https://factoriolab.github.io/staging (might need a private tab to get it to load the actual staging site).
It's still a work in progress but I think I resolved a couple bugs in that area.

**Comment by dcbroad3** [comment]
If it's not resolved (or you're not able to test it) I'll see if I can get it resolved in the next version.

**Comment by Lazula** [comment]
Yes, it's fixed on that staging link for all the mod sets. Didn't see that to test initially. Thanks!

**Comment by dcbroad3** [comment]
It's not generally suggested to test in staging but in this case you got lucky 🙂

**Comment by dcbroad3** [comment]
We can leave this open until the pr is merged to be clear

**Comment by Lazula** [comment]
I always try to test as many available environments as possible!
