### ISSUE TITLE
Ru translate

### ISSUE THREAD

**Issue by Art8900** [factoriolab/factoriolab#1384]
I want the site to be Russified ru.json file in the application
[ru.json](https://github.com/factoriolab/factoriolab/files/14866300/ru.json)

**Comment by dcbroad3** [comment]
I was creating a PR for this, and noticed that the app does not translate a few strings that it should. I am adding a few keys, if you are interested in translating these as well I will include them in the Russian language file. 
![image](https://github.com/factoriolab/factoriolab/assets/8430702/f255bf88-288a-4db3-a1f6-27a8d519e857)
![image](https://github.com/factoriolab/factoriolab/assets/8430702/6ccd3178-ebc9-4f22-8fdc-14f78dc235f1)
![image](https://github.com/factoriolab/factoriolab/assets/8430702/8b53d1ba-1cfb-43c7-b2b6-7966fff76dde)

**Comment by dcbroad3** [comment]
You can also see these changes at #1385

**Comment by dcbroad3** [comment]
I'll likely go ahead and merge the file you generated, but you're more than welcome to follow up with the additional translations, I can add them any time.
