### ISSUE TITLE
Printing (factorio + SE) doesn't print icons

### ISSUE THREAD

**Issue by bjbeare** [factoriolab/factoriolab#1391]
**Describe the bug**
When printing the factory output, the print out doesn't include an icon or description of the part or machine.

Pictures attached.
![Screenshot 2024-04-06 112316](https://github.com/factoriolab/factoriolab/assets/1189877/7d03b16d-6d02-467a-9e65-707c82df3a7a)
![Screenshot 2024-04-06 112257](https://github.com/factoriolab/factoriolab/assets/1189877/a1691546-a5a4-4652-b6aa-6fd8e05d420f)

**Comment by dcbroad3** [comment]
Make sure you have the option checked to 'print backgrounds'

This is in Firefox, but Chrome should have a similar option:
![image](https://github.com/factoriolab/factoriolab/assets/8430702/61d62f1a-5914-4f81-aafd-d2ebd3d61649)

**Comment by dcbroad3** [comment]
The same setting in Chrome:
![image](https://github.com/factoriolab/factoriolab/assets/8430702/45061165-e661-4d6b-91f5-ebc8abfcf152)

**Comment by dcbroad3** [comment]
Closing this issue, but feel free to follow up if you still have trouble with this.
