### ISSUE TITLE
add Lunar Landings mod

### ISSUE THREAD

**Issue by runelt99** [factoriolab/factoriolab#1404]
**Need it right now?**
Check out the [Wiki](https://github.com/factoriolab/factoriolab/wiki/Creating-a-new-mod-set) to see how to build the mod data and update the code yourself, and create a pull request or run the project locally!

**Have you checked whether this mod or set of mods has already been requested?**
[Check here](https://github.com/factoriolab/factoriolab/issues?q=is%3Aopen+is%3Aissue+label%3A%22mod+support%22)
If you find the mod you're looking for, add a "thumbs-up" reaction or a comment to the issue.

'No results matched your search.'

**What mod set are you requesting?**
"Lunar Landings" by [Xorimuth](https://mods.factorio.com/user/Xorimuth)

**What mods are included in this mod set?**
E.G. list all the distinct mods that should be included from the mod portal.

  | base | --- | -- | --
  | alien-biomes | 553K
  | alien-biomes-hr-terrain | 186K
  | SpidertronPatrols | 36.8K
  | se-space-trains | 45.2K
  | space-exploration-graphics | 440K
  | space-exploration-graphics-4 | 430K
  | space-exploration-graphics-5 | 429K

**Comment by Zipelsquerp** [comment]
bumping this request
