### ISSUE TITLE
Version is 0.0.0

### ISSUE THREAD

**Issue by USSX-Hares** [factoriolab/factoriolab#1412]
**Describe the bug**
Version in the bottom-right corner is `0.0.0`

**To Reproduce**
n/a

**Screenshots**
![image](https://github.com/factoriolab/factoriolab/assets/29100587/7d8a1b68-8a15-435d-9441-369378032208)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 126.0.6478.114

**Comment by dcbroad3** [comment]
Huh, thanks for pointing this out, I'm not sure what happened. I'll check this out as soon as possible.

**Comment by dcbroad3** [comment]
Oh, it's because the last commit actually shouldn't have triggered a release. I'll have to rethink that process.
