### ISSUE TITLE
Add ability to include ALL excluded recipes

### ISSUE THREAD

**Issue by USSX-Hares** [factoriolab/factoriolab#1413]
**Is your feature request related to a problem? Please describe.**
When you are working with overhaul mods, some products which are made from different production chains may be included.
I.e., FactorioLab *loves* making petroleum gas out of bioprocessing which (a) requires set-up vita processing and (b) requires a ridiculous amount of it as the gas is a occasional byproduct; there are many different yet similar cases for such a behaviour. Thus, you are disabling those recipes when they pop-out.

However, when this recipes are actually needed (i.e., you switched the target item while keeping the nicely configured machines & modules preset), those recopies are still disabled and thus the equation can't be solved at all.

**Describe the solution you'd like**
Add option/button which includes all manually excluded recipes, regardless of if they're visible or not. Basically revert all exclusions to their default state - similar to re-including all excluded *items*.

**Describe alternatives you've considered**
Alternative: A dialog pop-up/option which asks you if you want to try this with all recipes included, and including ones those were required but missing (and only them).

**Additional context**
For example: https://factoriolab.github.io/list?z=eJwVz01PAkEMgOF.s4dJJOyCCkdmCrvlS0ER5TIBBaOJgqBr8PD-dqeHPmk7bZM5yNYVzWaUizj4i2U729xmx8He5XF8l1g1jdwoErOVZV3jwmgk-nNjlph-W5Yi.CTqFINXa7.YZgrrTuxCKBNqLVknhlbOxzZl5czOVGkz2-Vu5HJ3H59jz9lM.IjDqPEmSnbKaeELfBcf8Iof4Sf4O.wSv8F.4X8JbUKHUBGGhAlhQVgSngg7wifhiLSQCbJAHpBH5AlZIRvkBXlDDsgJqZE.-g36J8oR5SflnvJAeaSsqZTqnmpF9YGiTTRHC7SFttFL9Aq9Rjtoeh2iI.QWnaFr9B09oWemLFizZU.tnOu5uXPn9GFXpMp1srr7D9iFhwo_&v=9

> **Solution is infeasible**
> Limit objectives may be too restrictive to satisfy Output objectives. Return code: ok, Simplex status: no_feasible

![image](https://github.com/factoriolab/factoriolab/assets/29100587/83d6919e-a998-405b-b8ce-3beae789364d)

**Comment by dcbroad3** [comment]
If you open the settings panel and go to the bottom in the advanced section, there is a button for excluded recipes that opens a dialog. In the header of that dialog there is a checkbox for "Include All". I think that should meet your needs?

**Comment by USSX-Hares** [comment]
> If you open the settings panel and go to the bottom in the advanced section, there is a button for excluded recipes that opens a dialog. In the header of that dialog there is a checkbox for "Include All". I think that should meet your needs?

Yeah. It should be in more obvious position then. Maybe modify the error message so it would help navigating there? Currently, it says about limits which I had nothing to do.

**Comment by dcbroad3** [comment]
I think multiple people have pointed out that dialog shouldn't be hidden at the bottom under advanced. I'll likely move it, but sure, adjusting the error message may also help.

**Comment by dcbroad3** [comment]
Excluded recipes picker was moved up a few versions back
