### ISSUE TITLE
Ultracube: Age of Cube

### ISSUE THREAD

**Issue by kienerxyzzy** [factoriolab/factoriolab#1419]
[](https://mods.factorio.com/mod/Ultracube)

**Comment by kienerxyzzy** [comment]
[https://mods.factorio.com/mod/Ultracube](https://mods.factorio.com/mod/Ultracube)

**Comment by dcbroad3** [comment]
Duplicate of #1334, which is closed as not planned. Ultracube enables recipes using lua scripts, which makes it nearly to impossible to parse. If anyone wants to generate Ultracube data by hand, I would consider accepting a PR, but I'm unable to use my data generation tool to do it.

**Comment by dcbroad3** [comment]
Duplicate of #1334, which is closed as not planned. Ultracube enables recipes using lua scripts, which makes it nearly to impossible to parse. If anyone wants to generate Ultracube data by hand, I would consider accepting a PR, but I'm unable to use my data generation tool to do it.
