### ISSUE TITLE
Overhaul wishlist

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factoriolab#1443]
- [x] Use standard URL query parameters wherever possible
  - [x] Use mod id as part of url path, e.g. <https://factoriolab.github.io/dsp?v=10>
  - [x] Spread individual settings into query parameters, e.g. `?preset=3`
  - [x] Save any array subsets as ranges
- [x] Minimize dependencies
  - [x] Remove ngx-google-analytics
  - [x] Remove @ngx-translate
  - [x] Remove elkjs & vis-data & vis-network
  - [x] Remove @ngrx
- [x] Check out stylelint
- [x] Use combined function/object type for `rational` as signals do
- [x] Try `CompressionStream`
- [x] Try removing all barrel files
- [x] Modernize @ngrx (if it cannot be removed)
- [x] Use standalone components throughout
- [x] Update ESLint and ESLint ruleset
  - [x] Enable all TypeChecked rules
- [x] Add coverage / test result comments to PR

**Comment by dcbroad3** [comment]
Removed:

- Use modern test framework to replace Karma/Jasmine (Jest?)
  - After much effort attempting to set up Jest, it still seemed to be insanely slow (killed after 350 seconds, vs 8 seconds for Jasmine)

**Comment by Dimava** [comment]
> Use modern test framework to replace Karma/Jasmine (Jest?)

Check Vitest, Bun:test and node:test

> Add const keyword to enum definitions

`const enum` is considered bad TS. Consider string literals like `'foo' | 'bar'`

> store data externally from the code repository

If repo size is below 100mb, this doesn't matter
If it's above, just zip your big jsons, should be enough

**Comment by Dimava** [comment]
> @Dimava the issue with the repo size is more about the fact that Git tracks all changes in the history of the repo, so even though the repo itself is just over 100mb, cloning the repo is just over 2GB currently (and will keep growing every time I update all the mod data).

https://rtyley.github.io/bfg-repo-cleaner/

**Comment by dcbroad3** [comment]
> What's the plan with removing NGRX? Going subject/signals with a service? A more lightweight dependency?

I'm experimenting with signals in a service. Reducer -> service/signal, action -> service method, selector -> computed. It seems to be working, although it's going to be a ton of work.

**Comment by michael-small** [comment]
> I'm experimenting with signals in a service. Reducer -> service/signal, action -> service method, selector -> computed. It seems to be working, although it's going to be a ton of work.

Nice, that sounds like a solid plan, good luck with that. 

I found this while I was considering making a Satisfactory calculator in Angular myself based around the one you were inspired by, but this already has it all. I found it from the subreddit and was floored to see such a well featured and modern Angular app. Good luck on the modernization.

Do you have some issues that would be good for a first contribution? Sorry if this is a common question, but I didn't see an immediate lead on that from the GH or Discord and don't want to step on any toes if you are open to random contributions.

**Comment by dcbroad3** [comment]
> > I'm experimenting with signals in a service. Reducer -> service/signal, action -> service method, selector -> computed. It seems to be working, although it's going to be a ton of work.
> 
> Nice, that sounds like a solid plan, good luck with that.
> 
> I found this while I was considering making a Satisfactory calculator in Angular myself based around the one you were inspired by, but this already has it all. I found it from the subreddit and was floored to see such a well featured and modern Angular app. Good luck on the modernization.
> 
> Do you have some issues that would be good for a first contribution? Sorry if this is a common question, but I didn't see an immediate lead on that from the GH or Discord and don't want to step on any toes if you are open to random contributions.

Sorry for the delayed reply. Appreciate your comments! I think of this project as part of my resume in a way so it's important to me that it reflects well. Part of the reason I'm removing ngrx is because, while I think it would be fine to leave it be, I wouldn't want anyone to think it would be my first choice on a new project today. I also use a lot of the code in this project as a reference when building new work projects, and that only really works if it's kept modernized. 

Anyway, I don't know if I have any immediate suggestions for contributions, but I can definitely say that contributions are welcome. I'll have to look around and see. The fact that I'm going through this overhaul does mean that moderately sized contributions may cause some painful merge conflicts. Honestly, I would say take a look at the backlog and see if anything piques your interest. If you find something, just ask and I can give you my thoughts on how feasible it seems. 

I don't really get many contributions or I'd try to be a little more organized!

**Comment by dcbroad3** [comment]
#1350 seems like a decent enough candidate for a first contribution, that might be my suggestion. It doesn't seem like it would be that large of a changeset to merge with the overhaul branch. The only problem is, I'm not really sure how to expose that feature in a way that's both unintrusive and discoverable.

**Comment by michael-small** [comment]
I'll look into that, thank you

**Comment by dcbroad3** [comment]
> I'll look into that, thank you
> 
> edit: when you say "It doesn't seem like it would be that large of a changeset to merge with the overhaul branch.", would you say I should branch off of that?

Whoops, I missed your edit. Yeah, I suppose it would probably make more sense to branch off of `next`.

**Comment by michael-small** [comment]
> Part of the reason I'm removing ngrx is because, while I think it would be fine to leave it be, I wouldn't want anyone to think it would be my first choice on a new project today.

Ah yeah, that's legit. I think if anything, I believe it is recommended by the NGRX team to start with Signal Store if a project were to pull in NGRX. I pulled it into a recent project that was started with the Component Store and I like it. NGXS also got a big update to use signals recently, they are keeping versions 1:1 with Angular now. But in my opinion as just some random guy, I think being consistent at whatever your state approach is is what counts.

> Yeah, I suppose it would probably make more sense to branch off of next.

Sounds good, thank you. I intend to take a crack at that issue when I fall off of Satisfactory 1.0 hype... or I hit a wall and don't want to get nuclear set up lol

**Comment by dcbroad3** [comment]
Ngrx is removed in the next branch now. I ended up creating two store classes that basically represent two types of simple signal stores. Half the code was just migrated from an old class of static methods. 
Having done it, I'm not really sure what kind of benefit ngrx signal stores would offer over rolling your own. It was a lot easier than I expected.

**Comment by michael-small** [comment]
Whoa nice, I'll have to check those changes out.

> Having done it, I'm not really sure what kind of benefit ngrx signal stores would offer over rolling your own. It was a lot easier than I expected.

Yeah, it has some cool benefits but that's not my place to pitch here unless you were curious. I'm looking at your changes and the classes you made are really cool, I can tell you put a lot of work into it.

**Comment by dcbroad3** [comment]
Remaining tasks moved to #1521 to address separately post release of Factorio: Space Age.
