### ISSUE TITLE
Issue with the flow visualization: too small when large amount of factories are used

### ISSUE THREAD

**Issue by Cometstreak** [factoriolab/factoriolab#1444]
Whenever I try using the program to visualize massive factories, the resulting mapping is so large that, within the small box given, it becomes essentially unreadable without having to zoom in, meaning that I can't easily take a picture for stuff like documentation

**Describe the solution you'd like**
Ideally some way to adjust the size of that window, and possibly have a way to export as a picture

**Describe alternatives you've considered**
fiddling around hoping to get it to a size that is readable

**Comment by dcbroad3** [comment]
The flow diagram is supposed to be zoomable, but I think I see why that doesn't really help; the diagram is way too narrow to be really usable. I'll have to look into ways to improve the sizing

**Comment by Apollys** [comment]
+1

The flowchart feature is really cool, but it's almost unusable for me as well. Ideally, it would be easy to click and drag to resize the module containing the flowchart visualization. Also, a simple option to download the flowchart as a `.png` image file could be very helpful (and perhaps easier to implement quickly).
