### ISSUE TITLE
Technology settings should affect factory presets

### ISSUE THREAD

**Issue by Xoriun** [factoriolab/factoriolab#1450]
When selecting which technologies are already research, only the recipes unlocked by these technologies are used.
Currently, the factory presets do not reflect these unlocks (i.e. the planner might still suggest electric furnaces even though they are not researched yet.) Especially for complex mod packs (BA, SeaBlock, SE) it is quite tedious to then check which machines are available and which are not.
It would be really nice if the presets would also be limited to the research technologies.

**Comment by dcbroad3** [comment]
Agreed. This was always part of the long term plan, but I hadn't opened an issue for it yet.

**Comment by dcbroad3** [comment]
Related,: https://discord.com/channels/806885678201831424/1166440112683499591
