### ISSUE TITLE
"Help me get started" wizard doesn't transition to main view

### ISSUE THREAD

**Issue by hoylemd** [factoriolab/factoriolab#1460]
**Describe the bug**
 It gets to the last step, where you enter the # of machine or items, but when you click OK nothing happens

**To Reproduce**

1. Go to https://factoriolab.github.io/
2. Click on 'Help me get started'
3. Pick an option
4. Pick a recipe/item
5. click 'Ok'

**Expected behavior**
Transition to main view with selected item/recipe etc

**Screenshots**
<img width="1114" alt="factoriolab_bug_report" src="https://github.com/user-attachments/assets/34587a72-c427-40e7-9c7a-d482fe9e38fa">

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 127

**Additional context**
No errors in the console either

**Comment by dcbroad3** [comment]
Something really weird is going on, because if I click it ~25 times, it will eventually load. If I then leave and go back to the wizard, it will work the first time.
