### ISSUE TITLE
Official/Unofficial Docker Image

### ISSUE THREAD

**Issue by nice3e3** [factoriolab/factoriolab#1463]
Are there are plans for releasing a docker image/dockerfile or anything simillar? Selfhosting the app would become much easier, the target audience is very small but it would definitely allow the project to grow and become more wide spread, easier reverse proxy setup, easier cloudflare tunneling. In case there aren't any I would gladly try my best to help release a pull request with a docker image or at least a docker file, another option is linuxserver.io

**Comment by dcbroad3** [comment]
It's just a pwa. Throw the build output in an nginx container and you're done, but it'll be exactly the same as if you used the real site. What's the use case exactly?

**Comment by nice3e3** [comment]
Compared to a nginx container it's way easier for begginers to use a docker image thats an all in one, for updates you'd do them manually or use a script but with a docker image it's simpler, it could promote self hosting in a community that's full of smart people that would probably use this as a good first project and it could introduce them to another big community or another hobby. I self host a website like factoriolab because I have a very bad internet connection that's a hit or miss (I do realize it's an app I load once and forget but still) and getting a nice domain with a cert instead of a lan ip address feels better and I do realize an nginx container ticks all of those boxes but I'd still want to help out the begginers

**Comment by dcbroad3** [comment]
I'm not convinced there's any value in this, though. Since there is no server component to this project, I don't know why you would self host using a container instead of just running the app locally in dev mode.
