### ISSUE TITLE
[mod request] Ultracube

### ISSUE THREAD

**Issue by Dimava** [factoriolab/factoriolab#1465]
**Need it right now?**
Check out the [Wiki](https://github.com/factoriolab/factoriolab/wiki/Creating-a-new-mod-set) to see how to build the mod data and update the code yourself, and create a pull request or run the project locally!

**Have you checked whether this mod or set of mods has already been requested?**
yes

**What mod set are you requesting?**Ultracube

**What mods are included in this mod set?**
Ultracube

**Comment by Mayeu** [comment]
This has already been requested multiple time.

You may want to close this issue and check: #1334, #1419

**Comment by Dimava** [comment]
Okay assign this to me then

**Comment by Mayeu** [comment]
I'm not the owner of the repo, nor part of the project, just a follower of it 🙂 

If you want to do it you can open a PR and see with @dcbroad3 for reviewing/merging 👍

**Comment by dcbroad3** [comment]
Thanks Mayeu. I'm open to accepting a PR. I don't normally assign out issues, but I can if you want.

**Comment by Dimava** [comment]
Hmm, so I can easily find out all the techs by cube-* name

**Comment by Dimava** [comment]
@dcbroad3 any ETA on live?
