### ISSUE TITLE
Missing new Satisfactory 1.0 alternates

### ISSUE THREAD

**Issue by Jessidhia** [factoriolab/factoriolab#1477]
**Describe the bug**
New alternate recipes from Satisfactory 1.0 are missing.

**To Reproduce**
For example, Basic Iron Ingot is not available in the list:

| Ingame Recipes list | FactorioLab search |
|---|---|
| ![image](https://github.com/user-attachments/assets/673566d5-9fa9-4ad9-9a4c-33d32594163e) | ![image](https://github.com/user-attachments/assets/8b6dd79c-466a-4f9f-83f0-bec271a88217) |

**Additional context**
The update to Satisfactory 1.0 overall is... partial; the version number on the calculator is still 0.7, belts only go up to Mk. 5, and also some renamed alternates are still under their old names (e.g. Rigour Motor -> Rigor Motor).

**Comment by dcbroad3** [comment]
What url are you using? The version has been updated to 1.0 and alternates have been updated. The basic iron ingot recipe is there. 

![Screenshot_20240915-115640](https://github.com/user-attachments/assets/2bd26569-5d48-49ca-b239-f8895cd8dc46)

The mk6 conveyor belts are still missing, but that's already tracked as #1476
