### ISSUE TITLE
Productivity modules in miners?

### ISSUE THREAD

**Issue by Dimava** [factoriolab/factoriolab#1478]
**Describe the bug**
![image](https://github.com/user-attachments/assets/b139d5cf-0c67-4e66-adac-77f254f7ab5b)

**To Reproduce**
https://factoriolab.github.io/list?s=***2&v=10
![image](https://github.com/user-attachments/assets/6b38df51-cedc-4f0a-bb44-e1d4033d44aa)

**Expected behavior**
![image](https://github.com/user-attachments/assets/0a8b0759-7fa2-4a27-910a-eda478429055)

**Comment by dcbroad3** [comment]
This isn't a bug, this is how that preset has always worked. There's actually no way with the current code to set it up so that a specific preset includes different configurations for different machines.

**Comment by dcbroad3** [comment]
I would recommend just setting it up however you want, and then saving that as a saved state instead. That way you can customize it to your heart's desire.
