### ISSUE TITLE
[Satisfactory] Add support for Production Amplifier mechanic

### ISSUE THREAD

**Issue by TacticalMook** [factoriolab/factoriolab#1480]
The 1.0 release of Satisfactory features a new mechanic that causes machines to output extra items while increasing power demand: [https://satisfactory.wiki.gg/wiki/Production_amplifier](https://satisfactory.wiki.gg/wiki/Production_amplifier)
(Similar to Productivity Modules in Factorio.)

I suppose the Machine column of the calculator is the right place for this, after the overclocking text field.

Or perhaps it's time to create new columns for Satisfactory's overclocking and production amplification mechanics?

**Comment by dcbroad3** [comment]
It seems like the linked article goes over the power requirements in great detail, but fails to indicate exactly how much each somersloop increases the actual output production. Am I missing it?

**Comment by happymy** [comment]
Smelter and Construct 
USE 1  somersloop  output x2.

Foundry,Assermbler,Refinery and Converter
USE 1  somersloop  output x1.5. 
USE 2  somersloop  output x2.

Manufacturer,Blender,Particle Accelerator and Quantum Encoder
USE 1  somersloop  output x1.25. 
USE 2  somersloop  output x1.5. 
USE 3  somersloop  output x1.75. 
USE 4  somersloop  output x2.

**Comment by dcbroad3** [comment]
Thanks, that makes sense. So it's always a range between 100% - 200% productivity, and it's a fraction between those based on the number of somersloop out of the maximum.
