### ISSUE TITLE
[Satisfactory] Names and Icons

### ISSUE THREAD

**Issue by Pepciorek** [factoriolab/factoriolab#1488]
"Ionized Fuel" is named just as "Fuel" and has its packaged form icon instead of fluid.
![image](https://github.com/user-attachments/assets/b1410027-d83d-46d9-a6c4-3b5fd4ecb1cd)
![image](https://github.com/user-attachments/assets/c7a2ba81-7d8c-404d-b14d-90d783e693c1)

Rocket fuel also has packaged icon instead of its fluid form.
![image](https://github.com/user-attachments/assets/61b1778d-88ae-4102-b08d-ddd46558d135)
![image](https://github.com/user-attachments/assets/f27408d6-bfd3-4bf9-9a6f-d04a4c44199f)

Supercomputer still has its old sprite.
![image](https://github.com/user-attachments/assets/908c5f55-d240-47e4-8e31-f48216c9b2b8)
![image](https://github.com/user-attachments/assets/c781efa7-e55e-401c-9c05-fd58297a9701)

Some raw resources also has changed icons.
![image](https://github.com/user-attachments/assets/3b9c3b7d-683e-42f9-9c7f-be77df3075c5)
![image](https://github.com/user-attachments/assets/64f77b9f-11ff-4c00-891b-acea72feab38)

![image](https://github.com/user-attachments/assets/789e2a35-0e80-4461-afb4-6a53fd7da756)
![image](https://github.com/user-attachments/assets/fa2c7d63-b068-4a77-8f0f-ba20f7d09efc)

**Comment by dcbroad3** [comment]
I would much prefer if you would condense issues like these into a single issue in the future if all of the problems are related to a specific data set
