### ISSUE TITLE
[Satisfactory] Gas Filter recipe incorrect

### ISSUE THREAD

**Issue by martinvonwittich** [factoriolab/factoriolab#1494]
**Describe the bug**
According to FactorioLab, Gas Filters require 4 Coal, 2 Fabric, 2 Rubber.

This is incorrect - in Satisfactory 1.0.0.2 (Build 367101), Gas Filters actually require 4 Coal, 2 Fabric, 2 Iron Plate:

![image](https://github.com/user-attachments/assets/87cd8e71-669b-458c-ba60-446e5cc2870f)

The official wiki confirms this: [Gas Mask - Official Satisfactory Wiki [satisfactory.wiki.gg]](https://satisfactory.wiki.gg/wiki/Gas_Mask)

If I'm not mistaken, this was apparently changed in 3e9e4e4efb16e4f6aa5d91ee8ecaf7f30f4e5b8d where the recipe changed from `"in":{"coal":5,"rubber":2,"fabric":2}` to `"in":{"fabric":2,"coal":4,"rubber":2},"out":{"gas-filter":1}`, whereas the wiki says:

> Changed cost from 5 Coal, 2 Rubber and 2 Fabric to 2 Fabric, 4 Coal and 2 Iron Plate

So this was probably just a simple mixup while updating the values for 1.0.

**To Reproduce**
1. Add Gas Filters to output list.

**Expected behavior**
Gas Filter recipe should be the same as the one ingame.

**Screenshots**

**Desktop (please complete the following information):**

- OS: NixOS
- Browser: Firefox
- Version: 130

**Comment by dcbroad3** [comment]
Thanks for the report. Can likely get this addressed tomorrow.
