### ISSUE TITLE
[Captain of Industry] Incorrect recipes for Core Fuel (Core Fuel Spent)

### ISSUE THREAD

**Issue by vibe-Chen** [factoriolab/factoriolab#1510]
**Describe the bug**
Incorrect recipes for Core Fuel (Core Fuel Spent).
On the web version of FactorioLab, the recipe Core Fuel (Core Fuel Spent) consumes 1 Core Fuel (Spent) per 60 time to produce 8 Core Fuel, which is incorrect.

**To Reproduce**
Simply check that recipe.
Or:
1.Add Core Fuel as target;
2.Disable both Blanket Fuel and Core Fuel recipe.

**Expected behavior**
The in-game recipe consumes **10** Core Fuel (Spent) instead of **1** per 60 time.

**Screenshots**
(Screenshot from web)
![图片](https://github.com/user-attachments/assets/1c5160c4-6b57-4b7e-93d0-022afddb8460)
(Screenshot from Wiki)
![图片](https://github.com/user-attachments/assets/9806f86a-5dd6-44e5-945d-a35f56287472)
(Screenshot in-game)
![图片](https://github.com/user-attachments/assets/00bc9ea6-c5ef-465e-ad93-cae6fe40343a)

**Platform:**
FactorioLab Web version 2.19.3

**Comment by dcbroad3** [comment]
Thanks for the report!
