### ISSUE TITLE
Multiple features broken

### ISSUE THREAD

**Issue by stevenwdv** [factoriolab/factoriolab#1525]
**Describe the bug**
Multiple features are broken on the site

**To Reproduce**

## Method 1

1. Go to [one of my saved states](https://factoriolab.github.io/list?z=eJxFkctuwjAURP8mi1lUcUiALliQp3FKIRIBqZur0idVKQUKhS749t6RAkjx0dj3NXa-iwqh7y1DzKWtK0AtLV0GU-FXC2ZiIsy8FyO-IBJ0NNhF7M3H3uITRtKVonhW5GvFfUC8KcpfRTZVxNzGMbeMJjkraqpCMeI27rLVrcJVjA6JkhixbMLkd8WA0aTDACuSNgf9MRCygSUcMWCrCMbbFF.MpstyrqgOwAo-fCmfABg9sjfAUYYPlBHrdk2xOPp1bO2OxJ44EBzsaMG1CFpw7OV4a0eDlgHLWtvRQcHJp48lfdCmG1OVlxtvNMc.cV6xvUjbV9k6hZIdG1GchRs1InfnUHQWP9d5u4tMP4BUqoleX.IFsAZPbdw8QpZcMrPsKvOrLK6tHvnifJGMf9XSSg-BVAGYI3YM9MVWwFKqP54Z77WHu1ONUEbSRxstSb2tOkDp7Y3.D1ymp-M_&v=10#step_4_machine_tab)
2. Works fine
3. Notice how the URL changes
4. Press F5
5. Nothing shows anymore: ![image](https://github.com/user-attachments/assets/1234420e-5e27-4d8d-89fc-15dab425d51a)

## Method 2

1. Create a new state
2. Try to add modules to a machine (and click Ok)
3. Nothing changes, modules are not added

**Expected behavior**
The site should work ;)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Both Firefox and Edge

**Additional context**
Probably related to #1443?

**Comment by dcbroad3** [comment]
I believe a fix for #2 is incoming: https://github.com/factoriolab/factoriolab/pull/1526
I'll look into your saved state. It's probably an issue with the migration.

**Comment by stevenwdv** [comment]
Thank you, that was fast! It works now
