### ISSUE TITLE
2.0/Space Age: Offshore pump recipes for Heavy Oil / Sulfuric Acid should be excluded by default

### ISSUE THREAD

**Issue by rmmh** [factoriolab/factoriolab#1547]
**Describe the bug**
The solver defaults to suggesting you use offshore pumps for heavy oil or sulfuric acid. These do not exist on Nauvis, and is less helpful than a proper chain going back to crude oil.

**To Reproduce**
Game: Factorio
Mod set: 2.0/Space Age
Objective: Sulfuric Acid

**Expected behavior**
I want to see a solution rooted in crude oil.

**Additional context**
The Space Exploration modset by default excludes unhelpful recipes like core processing.

**Comment by dcbroad3** [comment]
I think I would effectively consider this a duplicate of #1540
