### ISSUE TITLE
Quality Effect on Modules

### ISSUE THREAD

**Issue by boomshroom** [factoriolab/factoriolab#1552]
**Describe the bug**
When selecting to apply a module to a machine of a quality higher than normal, the calculator will scale all of the module's stats by the quality bonus rather than just the primary stat.

**To Reproduce**

1. Open any of the places where you can select a module
2. See the stats of the normal quality version of a module
3. See the stats of a higher quality version of a module, where all of them are greater than the normal quality

**Expected behavior**
Effects such as the speed penalty of productivity and quality modules, or the energy consumption penalty of speed and productivity modules, should remain the same across different quality versions of the same module.

**Desktop (please complete the following information):**

- OS: Linux
- Browser Brave
- Version 1.70.123

**Additional context**
Machines do not appear to have this issue and they correctly only scale the stats actually affected by quality. The problem appears to be exclusive to modules. Beacons have a different problem, namely that they aren't shown as being affected by quality at all, when quality should instead increase efficiency and decrease energy consumption.

**Comment by dcbroad3** [comment]
Thanks for the report. The behavior is based on the wiki for quality, which didn't include many of these minutia. 

Are you aware of the formula for the effects quality has on beacons? The wiki entry does not last the actual percentage effect.

**Comment by boomshroom** [comment]
Checking the Factoriopedia:
| Quality | Effect |
|--------|--------|
| Normal | 1.5 |
| Uncommon | 1.7 |
| Rare | 1.9 |
| Epic | 2.1 |
| Legendary | 2.5 | 

It's the same kind of linear scaling as with other stats, but going from 1.5 to 2.5 instead of 1 to 2.5, so each step is +.2 instead of +.3. It's then this times the square root of the number of beacons for the total effect (or divided by the square root of the number of beacons for the effect of each individual beacon).

**Comment by boomshroom** [comment]
Taking a closer look, the machines don't seem to actually match up, and the few that I quickly checked seem to have a double increase at both Uncommon and Legendary rather than just Legendary, resulting in every tier above Normal having a higher reported crafting speed than in-game.

**Comment by dcbroad3** [comment]
If I'm following you, that should be fixed by #1556

**Comment by dcbroad3** [comment]
Opened #1558 for beacon quality
