### ISSUE TITLE
Asteroid crushing recipes crash the calculation

### ISSUE THREAD

**Issue by amdepott** [factoriolab/factoriolab#1555]
**Describe the bug**
When selecting asteroid crushing recipes as the only possible source of ingredients, the calculation crashes with error 
"Solution is infeasible Limit objectives may be too restrictive to satisfy Output objectives. Return code: ok, Simplex status: no_feasible"

**To Reproduce**

1. Select iron ore as the item being made
2. Under "Recipes", deselect mining and recycling recipes, allowing only asteroid crushing
3. Calculation crashes with error
"Solution is infeasible Limit objectives may be too restrictive to satisfy Output objectives. Return code: ok, Simplex status: no_feasible"

**Expected behavior**
Displays the number of asteroids and crushers required to meet the input production level

**Screenshots**
![image](https://github.com/user-attachments/assets/f495bfeb-cc2f-4319-84bd-623569c7da89)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox 
- Version: 131.0.3

**Additional context**
Happens with ice, carbon, and iron ore, and if you select Machines and any of the asteroid crushing recipes

**Comment by amdepott** [comment]
According to this discord post, if you manually add asteroids as input items, the calculation works as expected.

**Comment by dcbroad3** [comment]
Could you share a link?

**Comment by amdepott** [comment]
https://factoriolab.github.io/spa/list?o=iron-plate**3&rex=F3*Im&v=11
