### ISSUE TITLE
Space Age: Foundry Base Productivity

### ISSUE THREAD

**Issue by Shadefang** [factoriolab/factoriolab#1563]
**Describe the bug**
The Factorio: Space Age planner does not appear to take the foundry's base 50% productivity into account.

**To Reproduce**

Set foundry as the preferred machine
Select an item the foundry can craft (tested with iron plates, gears, belts, and foundries)
See that the recipe section is stating the base ratio, with no productivity.

the easiest specific place to see this without knowing the recipes off the top of your head is:
Create a yellow belt recipe
Swap the machine assigned to yellow belts between foundry and assembly machine 1
Note that the required inputs do not change

**Expected behavior**
The calculator should factor in the foundry's 50% base productivity.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome

**Additional context**
Note that the foundry's productivity bonus does not seem to be restricted to intermediate products like modules are, meaning it should be applying to the belts/pipes/machines it makes in addition to things like plates and gears.

**Comment by dcbroad3** [comment]
![Screenshot_20241025-185844](https://github.com/user-attachments/assets/47d3cd5b-7ffd-4a6a-9c15-c5d410d0cf84)

It looks like it's accounting for productivity to me

**Comment by dcbroad3** [comment]
![Screenshot_20241025-192035](https://github.com/user-attachments/assets/8b0cef18-ad64-4f82-802c-587b7a08649c)

This is what I see when I open that link, the bonus does seem to be applied. 
What version does it say at the bottom of the page?

**Comment by Shadefang** [comment]
Yeah, looks like it's likely I was running an out of date version, as a hard refresh seems to have fixed the issue. (I decided to see if that fixed it after a test in Firefox showed it working properly, apologies for not grabbing the version number before trying that.)

So almost certainly was an issue on my end as opposed to the site itself.

**Comment by dcbroad3** [comment]
Well, that feature wasn't properly implemented earlier this week, but anyway, glad it's working for you now!
