### ISSUE TITLE
Factorio Space Age: Pumps are modified by the belt stack size

### ISSUE THREAD

**Issue by SpaceBroetchen** [factoriolab/factoriolab#1585]
**Description**
If you select a stack size for a belt the required pumps are calculated wrong

**To Reproduce**

1. Select the "Space Age" mod preset
2. Add a fluid recipe
3. Set the default belt stack size > 1
4. Take a look at the required pumps for the recipe, they will be smaller than act

**Expected behavior**
I expect the pump amount to be independent from the default stack size.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/16fb7518-a6d2-4080-9022-5df1a4ac0328)
![grafik](https://github.com/user-attachments/assets/43775850-8075-463c-82e7-3144a7aa103d)

**Desktop:**
- OS: Windows 10 version 22H2 
- Browser Firefox
- Version 132.0 (64-Bit)

**Additional context**
[Here an example](https://factoriolab.github.io/spa/list?o=water*2000&odr=0&ist=4&v=11)

**Comment by dcbroad3** [comment]
Good catch, thanks for the report.
