### ISSUE TITLE
Space Age: Scrap processing generates random output. VERY random

### ISSUE THREAD

**Issue by USSX-Hares** [factoriolab/factoriolab#1588]
### Steps to Reproduce
https://factoriolab.github.io/spa/list?z=eJwFwTEKgDAQBMDfbHHVJbGw2UYNCJJGxAcoKQKGiIVY3dudaYxNvKqqiEfjNEvXS5CATBlQmURR8sfxRjkyB9T6cLfVFou2WcJRC73iaicjXjr3A6KAF6k_&v=11#step_27_recipe_tab

1. Factorio -> Space Age
2. Planets: Fulgora only
3. Request:
   * Maximize Holmium solution
   * Limit 48 machines making scrap reclining

![image](https://github.com/user-attachments/assets/2529d82a-473d-4377-b0df-e7eb2ba12a6a)

#### Expected
- Byproducts are ignored

#### Actual
Produces:
- Blue underground belts (26/m)
- Heat exchangers (0.06/m)
- Personal roboports (637/m)
- Recyclers (9/m)
- Centrifuges (3.4/m)
- Landfill (11/m)
- Concrete out of hazardous concrete out of concrete

![image](https://github.com/user-attachments/assets/9bf28841-ad66-4125-a026-67277afe597a)
![image](https://github.com/user-attachments/assets/f966b0ae-1d3e-47b1-843d-8a273e4e8d6e)

### Environment:
- OS: Win10
- Browser: Chrome 129.0.6668.101 
- FactorioLab 3.5.5

### Additional context
```
Solved, 15ms, cost: -2639999999447.83
```

**Comment by dcbroad3** [comment]
While I fully appreciate that this is not the desired output, I'm not really sure this qualifies as a bug. What specifically about the solution to you think is a bug? The recycling recipes are kind of a nightmare, but you can exclude them or set the tech to not researched.

**Comment by USSX-Hares** [comment]
> While I fully appreciate that this is not the desired output, I'm not really sure this qualifies as a bug. What specifically about the solution to you think is a bug? The recycling recipes are kind of a nightmare, but you can exclude them or set the tech to not researched.

Scrap recycling produces stone, ice, and holmium ore, all of which are required to make a holmiun solution and none of which can be obtained – in any manner – by assembling or disassembling any other resource or material (except for rock formations & ruins) on Fulgora.

**Comment by dcbroad3** [comment]
Hm. I'm a bit baffled to why it considers that the ideal solution, I admit. I don't see how producing a surplus of random items would improve the solution cost. 
You can assign a surplus cost and it will at least stop that nonsense, but overall the solution still seems nonsensical to me. I'll have to look into it later, but I have to assume the solver has a reason for what it's doing.

**Comment by dcbroad3** [comment]
OK, I think I see what the problem is. 
You've set the "Maximize" value extremely high, at 20K. Generally I use a value of "1". 
Because the value is SO, high, effectively, I think the numbers get so huge that the whole solver starts to lose precision with the massive cost numbers, and suddenly it seems 'just fine' to have all this extra production. 
Setting your maximize value to "1", it looks like the results are perfectly reasonable. 

All this being said - I don't think this is a "you messed up" situation. The solver really shouldn't care _what_ you put in that field, it should always reduce it down to a _ratio_ of values for all maximize objectives. I'm going to add in some logic that will automatically sum up all the maximize objective values, and divide so that they all sum up to "1".

**Comment by USSX-Hares** [comment]
> OK, I think I see what the problem is. You've set the "Maximize" value extremely high, at 20K. Generally I use a value of "1". Because the value is SO, high, effectively, I think the numbers get so huge that the whole solver starts to lose precision with the massive cost numbers, and suddenly it seems 'just fine' to have all this extra production. Setting your maximize value to "1", it looks like the results are perfectly reasonable.
> 
> All this being said - I don't think this is a "you messed up" situation. The solver really shouldn't care _what_ you put in that field, it should always reduce it down to a _ratio_ of values for all maximize objectives. I'm going to add in some logic that will automatically sum up all the maximize objective values, and divide so that they all sum up to "1".

BTW, I was just requesting 20k units per minute and then switched the option
