### ISSUE TITLE
[Space Age ; minor issue] wrong technology for unlocking iron stick

### ISSUE THREAD

**Issue by Factorionaut** [factoriolab/factoriolab#1593]
**Describe the bug**
The app thinks that iron stick is unlocked by "Circuit Network" research and not "Electric energy distribution 1"

**Screenshots**
![2024-11-03_175534](https://github.com/user-attachments/assets/d7913190-bbe6-48ee-91c9-5d439f99e5b5)

As you can see, iron stick is missing from it's correct technology unlocks

This is how it looks in game:
![2024-11-03_180507](https://github.com/user-attachments/assets/b97ccaf5-cb32-412a-b493-7e806006d371)

**Comment by dcbroad3** [comment]
![image](https://github.com/user-attachments/assets/7fef07d2-0c38-4e5b-b855-5045c27ebed6)
