### ISSUE TITLE
In Space Age, Gleba can get water from offshore pumps

### ISSUE THREAD

**Issue by cwitty** [factoriolab/factoriolab#1596]
**Describe the bug**
If I ask for a recipe that requires water with the location restricted to Gleba, it uses strange imports instead of suggesting an offshore pump.

**To Reproduce**
With the Space Age preset, add the item "water"; then restrict the location to Gleba.  You get something like: https://factoriolab.github.io/spa/list?o=water&loc=D&v=11 which suggests getting water via ammoniacal solution (which is only available on Aquilo).

**Expected behavior**
I expected it to suggest getting water from an offshore pump, like it does if you restrict the location to Nauvis.  (Nauvis and Gleba are the only two planets where you can get water from offshore pumps.)

Desktop (please complete the following information):
Chrome: Version 116.0.5845.180 (Official Build) (64-bit)
Windows 10

**Comment by dcbroad3** [comment]
I must have overcorrected earlier today. Haven't gotten to gleba yet myself but it appeared the water tile was only present on nauvis based on the data. Should be able to fix this tonight or tomorrow morning.
