### ISSUE TITLE
Remove productivity from crafting machines when the productivity is over the max.

### ISSUE THREAD

**Issue by BestUser14** [factoriolab/factoriolab#1602]
**Is your feature request related to a problem? Please describe.**
setting researched productivity to 300% keeps productivity modules on crafters for steel and such even when that wouldnt do anything in game

**Describe the solution you'd like**
disallow productivity modules on crafting machines when their productivity reaches over the max

**Describe alternatives you've considered**
i dont want to manually replace each recipe with speed

**Comment by dcbroad3** [comment]
Hm. Currently the calculator isn't even capping productivity, I need to add that. Having it automatically block productivity modules seems drastic, in what situation would this apply to multiple recipes at once? Wouldn't this only become tedious when you reach an insanely high productivity on several different recipes?

**Comment by BestUser14** [comment]
doesn't it cap if you have just a base 300% productivity from research? in that case you wouldn't want productivity modules on steel, low density structures, processing units, etc. but you would want them on yellow science and miners etc

**Comment by dcbroad3** [comment]
But you would have to individually reach 300% productivity on each of those recipes separately. You already have to enter the research prod bonus for each of those recipes separately, I don't think it's much extra work to also update the modules for that recipe..

**Comment by BestUser14** [comment]
"I played the game from start to finish once again, it took 240 hours, which is still way too much. But it needs to be considered that I went quite heavy with the factory size, trying to get almost everything in legendary quality, with the goal of 1 million science per minute (SPM).
I haven't reached 1M SPM yet, but I might get there before we release :). " https://www.factorio.com/blog/post/fff-417

It would only take an hour to reach 250% productivity for steel which would max out the foundries at 1M spm.

I didnt know you could change the modules per recipe so ill try that for now

**Comment by BestUser14** [comment]
nevermind its not that bad to change the recipes

**Comment by dcbroad3** [comment]
I definitely think an indication the recipe is over 300% prod could be useful at that stage
