### ISSUE TITLE
Space Age: can't get rid of "Solution is infeasible"

### ISSUE THREAD

**Issue by lewie-donckers** [factoriolab/factoriolab#1609]
**Describe the bug**
When I'm fiddling around with a production tree (selecting my preferred recipe or machine) I often end up in a situation where I get the "Solution is infeasible" error message. But I can't seem to get rid of it. Because once the solution is infeasible you are no longer able/allowed to change selected recipes.

**Expected behavior**
Not to get the error message. Or a way to reselect recipes until the solution is feasible again.

**Screenshots**
![image](https://github.com/user-attachments/assets/1ddd3586-aa3c-416b-a89d-470db1a06614)

**Comment by dcbroad3** [comment]
I don't really know how to just "not get the error message". I pushed a change yesterday (and improved it today) to _try_ to catch simple cases where you can run into infeasibility, but it's far from foolproof. 

For what it's worth, you can still change the selected recipes in the settings panel.
![image](https://github.com/user-attachments/assets/b4e2074b-fb92-4435-b405-643108decaa8)

**Comment by lewie-donckers** [comment]
ah! that's where it is! i thought i looked everywhere. i can at least fix it now when i run into it again. thanks!
