### ISSUE TITLE
Space age: calculator suggest to import and recycle spidertrons in order to create rocket parts on Gleba

### ISSUE THREAD

**Issue by arthens** [factoriolab/factoriolab#1624]
**Describe the bug**
Every time I try to calculate how to produce rocket parts on Gleba the calculator suggest I import and recycle spidertrons.
This is true even if research for other planets are disabled - even with spidertrons and recyclers not researched, the calculator still suggest I need to import and recycle spidetrons.

**To Reproduce**

1. Open the calculator
2. Add rocket parts
3. Select Gleba
4. (Optional: disable other planet research)
5. Recycling spidertrons is still the suggested way

The beahaviour can be seen at [this link](https://factoriolab.github.io/spa/list?o=rocket-part&tre=A~G*I*P~Y*c*g~C3*C5*C7~DR*Db~Dh*Dj~Dq*Du~Dx*D8~ED*EG~EH&loc=D&v=11)

**Expected behavior**
Calculator should use local resources and processed and not suggest importing materials.

**Screenshots**

![spidertrons](https://github.com/user-attachments/assets/cbbb47bb-d0b8-480c-aa4c-51c779412639)

![materials](https://github.com/user-attachments/assets/b35722cb-d190-4f3f-b547-87360560fbbc)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome and Firefox

**Comment by arthens** [comment]
Sharing the workaround I found:
Recycling of individual products can be disabled under the "Unsorted" tab of the "Recipe excluded" modal. Doing this produces the right results.

![workaround](https://github.com/user-attachments/assets/81133b30-7297-4ff6-874b-8c0326903bd1)

**Comment by dcbroad3** [comment]
I've been meaning to add gleba agriculture tower recipes, I'll use this ticket for that at least. I'm also planning to add a recycling cost modifier, so you can forcefully make recycling expensive even without excluding the recipes.
