### ISSUE TITLE
Ability to reset all of the settings for a particular saved state.

### ISSUE THREAD

**Issue by NicolBolas** [factoriolab/factoriolab#1637]
**Is your feature request related to a problem? Please describe.**
There are a lot of settings in the UI, and some of them are not obvious. There's a big menu of ignored recipes, but things like ignoring items is not listed in a menu. When creating a new state, it always does so by copying settings from the current state. And since not all settings are obvious, sometimes you get ignored items or manually-set building selections for recipes tagging along across several new saved states.

**Describe the solution you'd like**
There should be a button you can press that clears *all* settings from the current state, resetting everything back to the default.

**Comment by dcbroad3** [comment]
If you click the game icon at the top of the site, it resets everything to defaults. Would that work for you?

**Comment by dcbroad3** [comment]
Closing, let me know if that suggestion doesn't help.
