### ISSUE TITLE
"Maximize" objective sometimes compute sub-optimal results

### ISSUE THREAD

**Issue by zhuyifei1999** [factoriolab/factoriolab#1638]
**Describe the bug**
I was trying to answer the question "how fast can you produce tier 3 modules given 1 full green belt of scrap". With a tier 3 module as output, and scrap as limit, I got 4.2. But with module as "maximize", and scrap as input, I only got 3.1.

**To Reproduce**

[Module as output link](https://factoriolab.github.io/spa/list?z=eJwlyrtSwkAYQOG3SXFmdodAMLtFCjZACIiIIIidQFTkEkRQoNhn93csvplTnDJxIZGuBmWS7iGk9lfxf63mRdIMDsU5aXhXwUU-3SFbevTNjGbu20PaI5.lZD2fncmuvpPT6fl8Sj7z.TVF3ReGeOPjC3GN2GC6mAFmjJlhlpiVN2vMHnPCXDERxmJTbAfbxz5gp9g59g27wX5iv7EVbB2rUE1UjrpDjVBPqAXqHbVFHVA.qBB1g9LoFrqLHqDH6Bl6iV6hd-gv9BldRce4RkO0RU.ci0fxLArxIUpxFBdREwbnnMjErRiKiXgRr2It9uLknYuC7faQTHw.2JSLpBV8J2H4C1p0Yjo_&v=11), [module as "maximize" link](https://factoriolab.github.io/spa/list?z=eJwVyrtSwkAYQOG3SXFmdodwMbtFCjaBEBARQRA7gajIJYigQLHP7k.xzZzilLELgWpQxskeQsJbRbeqBat5EafBoTjHTe8quLpPdsiWHH2akea-PaQ98llO1vPZmezqOzmdns-n5DPfX1M0fGGINj66ENWIDKaLGWDGmBlmiVl5s8bsMSfMFVPHWGyC7WD72CfsFDvHfmA32G.sL7aCbWAVKkXlqAfUCPWCWqA-UVvUAfWHClF3KI1uobvoAXqMnqGX6BV6h.5Bn9FVdIRrNkVb9MSjeBavohBfohRHcRE1YXDOiUzci6GYiDfxLtZiL07euXqw3R7iie8Hm3IRt4LfOAz.AUNQYio_&v=11)

The module as output is bottlenecked by red circuits, and it compensates by recycling blues for greens and assembling additional greens from recycled iron and wires, and recycling LDS for plastic, then assembling the reds out of those, consuming all plastic from recycled LDS. The module as "maximize" is still bottlenecked by red circuits, but does not compensate, leaving a lot of excess blue circuits, LDS, and wires.

**Expected behavior**
They should produce the same result.

**Screenshots**

![Screenshot_2024-12-01_09-25-15](https://github.com/user-attachments/assets/2f43e805-d46d-4cf9-a73e-9fd28742c084)
![Screenshot_2024-12-01_09-26-46](https://github.com/user-attachments/assets/f380fae4-a718-46a7-8feb-d60535d0ca5c)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Linux
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] FactorioLab 3.8.4. Firefox 132

**Additional context**

I heavily restricted allowed recipes to strictly have only scrap be the input (other than the "additional ingredient" for the tier 3 module). Since LDS recycle is the only way to get more plastic, with every other method already being bottlenecked and no coal available on Fulgora surface, I don't see any use in adding any more recipes.

The "maximize" option gets better if I *disallow* gear recycling, from 3.1 -> 3.3. The "output" option gets worse as expected (since fewer reds can be assembled) from 4.2 -> 3.9.

**Comment by dcbroad3** [comment]
By default, the cost of recycling recipes is multiplied by 1000, to discourage the solver from using recycling to produce everything. On Fulgora, I recommend setting this to zero. By doing that alone, I get better results from your link: 
https://factoriolab.github.io/spa/list?z=eJwVyrtSwkAYQOG3SXFmdodwMbtFCjaBEBARQRA7gajIJYigQLHP7k.xzZzilLELgWpQxskeQsJbRbeqBat5EafBoTjHTe8quLpPdsiWHH2akea-PaQ98llO1vPZmezqOzmdns-n5DPfX1M0fGGINj66ENWIDKaLGWDGmBlmiVl5s8bsMSfMFVPHWGyC7WD72CfsFDvHfmA32G.sL7aCbWAVKkXlqAfUCPWCWqA-UVvUAfWHClF3KI1uobvoAXqMnqGX6BV6h.5Bn9FVdIRrNkVb9MSjeBavohBfohRHcRE1YXDOiUzci6GYiDfxLtZiL07euXqw3R7iie8Hm3IRt4LFoYgrwW8chv-YfWP3&v=11

**Comment by zhuyifei1999** [comment]
Ah ok, I haven't looked into the code so I'm not fully sure what the advanced settings are, and I don't generally tinker around things I don't know.

Though it sounds unintuitive to me that it would not produce more with the excess. Is it that the recycling of LDS for plastic being discouraged?

That said, the solver seems to have a tendency to recycle spidertron for parts and use that to produce things ([example](https://factoriolab.github.io/spa/list?o=productivity-module-3*4.2&o=scrap**1*3&o=biter-egg**1*3&ibe=turbo-transport-belt&mmr=electromagnetic-plant~recycler&loc=E&v=11)) so I had to heavily restrict the allowed recipes. It sounds like the recycling discouragement isn't enough in most circumstances.

**Comment by dcbroad3** [comment]
Yeah, tweaking cost settings is generally a very advanced thing to do, but it's called for a lot more often now in space age. It's something I'll have to work on at some point, but in any case, I don't think this is a true bug and so I will close this issue.
