### ISSUE TITLE
Red Science Pack Not Giving Recipe

### ISSUE THREAD

**Issue by tlivesay** [factoriolab/factoriolab#1648]
**Describe the bug**
No results found for recipe Automation science pack

**To Reproduce**
Filter to Space Age
Filter to Nauvis
(all recipes unlocked, other settings are defaults)
Click add items
Select "Automation science pack"
Click to select included recipes for this item

"No results found" is what shows. see screenshot.

**Expected behavior**
The recipe copper plate + iron gear should be there, but there's no valid recipe.

**Screenshots**
![image](https://github.com/user-attachments/assets/193f81ce-c9aa-4ca3-9c67-eaa2327d7c5a)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Version: 133.0

**Additional context**
I feel like I'm missing something simple here

**Comment by tlivesay** [comment]
The recipe is there in the tab too, so the data isn't missing it's just not showing up where it needs to.
![image](https://github.com/user-attachments/assets/854018a9-6dcb-44ec-a439-9d25479adb7e)

**Comment by dcbroad3** [comment]
I think you've chosen the automation science pack technology, instead of the item (which is in the intermediate products tab). The technology is triggered by an action in the game, so it doesn't have a recipe, but the recipe for most technologies includes science packs.

**Comment by dcbroad3** [comment]
For future reference, you can share the url in the address bar so that I can see your exact configuration.

**Comment by tlivesay** [comment]
Thanks, here it is! https://factoriolab.github.io/spa/list?z=eJzLt3Wt1DI2UEuy1YpXy7V11dIyAFIhICqzuMTWWK0otcLWyULLSbfOSU.L2UnLOU0tN7fINrDOq861LqQuQi03KdXWQC0nP9nWSa3M1tAQALPwF7o_&v=11
