### ISSUE TITLE
remove quality rocket part recipes and rocket part recycling 

### ISSUE THREAD

**Issue by gfrodo** [factoriolab/factoriolab#1656]
With factorio 2.0 and space age, you can select legendary rocket parts or recycle rocket parts of any quality in the calculator, even though this is not possible in the game.

Probably some special handling is needed to avoid generating recycling recipes for rocket parts as well as the quality recipes.

**Comment by dcbroad3** [comment]
I'm torn on whether this is truly a bug. 

The game specifies a stack size and rocket capacity for rocket parts, and generates recycling recipes for rocket parts, and there's really nothing special about the rocket part item that indicates "this can't be quality". You can't put quality modules in a rocket silo, but if there was a mod that allowed crafting them in an assembler, I think the game would allow it. 

In other words, it would be very difficult to do this in a way that is safe with regards to mods. Yes, it's not possible to generate quality rocket parts or recycle rocket parts in space age, but that doesn't mean mods couldn't do it. Determining whether it's actually _possible_ to do it in a given mod set would require some extensive logic. 

1) To determine whether an item is a rocket part that does not have quality
    - You would have to determine whether any recipes producing the item allow quality modules
    - You would have to ensure it cannot be produced in a machine that allows quality modules
1) To determine whether a recycling recipe for rocket parts is not viable
    - I'm not even sure how you would? I assume you would have to determine whether the input item can only be produced in a rocket silo? That is a lot harder than it sounds.

I think the easiest answer for me is to say to simply ignore it.

**Comment by gfrodo** [comment]
The "recycling rocket part" recipe has been removed in factorio 2.0.34, so it should also disappear from the calculator, once the dataset is imported again
