### ISSUE TITLE
Add support to Archipelago.

### ISSUE THREAD

**Issue by DEMEMZEA** [factoriolab/factoriolab#1657]
**Is your feature request related to a problem? Please describe.**
Archipelago is a multi world randomiser that randomises the crafting recipes of some items. In my case, science packs ( and some researches ), but idk if it can alter other recipes as well

**Describe the solution you'd like**
I'd like to be able to paste an archipelago file and the recipes that needed to be converted would be to their archipelago versions

**Describe alternatives you've considered**
Just inputing the items that take to make the science and their respective values instead of the science

**Additional context**

**Comment by dcbroad3** [comment]
Is this a Factorio mod?

**Comment by DEMEMZEA** [comment]
No, I'm talking about [Archipelago](https://archipelago.gg/), the cross-game modification system which randomizes different games, then uses the result to build a single unified multi-player game, sorry for not being clearer

**Comment by DEMEMZEA** [comment]
No, I'm talking about [Archipelago](https://archipelago.gg/), the cross-game modification system which randomizes different games, then uses the result to build a single unified multi-player game, sorry for not being clearer.

**Comment by dcbroad3** [comment]
I don't see how this would be possible to support. Since it is a randomizer, by nature it is not possible to build a single data set to support it. #1452 might help users who are using Archipelago, but at this time I don't believe I would ever build support for Archipelago specifically.
