### ISSUE TITLE
DSP: Calculator does not show machine count for some recipe maximization

### ISSUE THREAD

**Issue by wongjn** [factoriolab/factoriolab#1661]
## Describe the bug

Under certain conditions, no machine count is visible for a maxmimize calculation.

## To Reproduce

1. Select Dyson Sphere Program.
2. Select *Iron Veins* product, 20 limit.
3. Select *Iron Ingot* product, maximize.
4. See the *Iron Ingot* item in the *List* does not have a machine count.

This can be reproduced with other products, like *Silicon Veins* with *High-purity Silicon*, *Titanium Veins* with *Titanium Ingot*, etc.

## Expected behavior

The *Iron Ingot* item in the *List* should have a machine count.

## Screenshots

![image](https://github.com/user-attachments/assets/88f2f885-ed1e-4253-a33e-c33e2c1f3221)

Switching from *Iron Ingot* to *Gear* can also continue to exhibit the erroneous behavior:

![image](https://github.com/user-attachments/assets/67f108dc-635d-400f-a6ce-a8d86723ff5d)

## Desktop (please complete the following information)

- OS: Windows 11
- Browser: Firefox
- Version: 133.0.3 (64-bit)

**Comment by dcbroad3** [comment]
This should be fixed in version 3.8.10, by #1674
