### ISSUE TITLE
Space Age: Add option to disable recycling recipes

### ISSUE THREAD

**Issue by USSX-Hares** [factoriolab/factoriolab#1666]
**Is your feature request related to a problem? Please describe.**
Most of the time, when you ask the system to show optimal solution, it will dump something like "make copper cables by recycling red circuits from scrap" when you even added molten copper input.

**Describe the solution you'd like**
A toggle that enables/disables recycling recipes

**Describe alternatives you've considered**
Drastically lower priority of recycling recipes

**Comment by dcbroad3** [comment]
That's largely what this button was for, although it's a little more complicated now that many of the recycling recipes are mixed in to other tabs
![image](https://github.com/user-attachments/assets/67b491fd-ee22-4cac-a850-d3c8d33c06c8)

**Comment by dcbroad3** [comment]
I also added this cost field you can increase if needed
![image](https://github.com/user-attachments/assets/c1d28302-b88d-46f3-bc1e-7c95bfafdb0c)

**Comment by USSX-Hares** [comment]
> That's largely what this button was for, although it's a little more complicated now that many of the recycling recipes are mixed in to other tabs ![image](https://private-user-images.githubusercontent.com/8430702/396992045-67b491fd-ee22-4cac-a850-d3c8d33c06c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NjE1NDUsIm5iZiI6MTczNDU2MTI0NSwicGF0aCI6Ii84NDMwNzAyLzM5Njk5MjA0NS02N2I0OTFmZC1lZTIyLTRjYWMtYTg1MC1kM2M4ZDMzYzA2YzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMjIzNDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWExZDk0ZGRjNzY4MTAzOTNkZDEyZTg1M2QwZWRkM2I5YmQ0ZTM2YTcwZWI4NTk5MTFkNzhkOGJjNThkYzRjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v52GA45EQdCkjQhmcr33sGIVagn2Ttqs6qSh3QGIF_Q)

Wait, where's that button is located? I can't find it.

**Comment by dcbroad3** [comment]
As a last option, you can also set the recycling technology as not researched, and that will automatically exclude all the recycling options.

If none of these options works for you, let me know, but I'm not sure how much more can be done.
