### ISSUE TITLE
Incorrect quality modifiers in higher quality quality modules

### ISSUE THREAD

**Issue by hackguy25** [factoriolab/factoriolab#1673]
Some quality tiers of quality modules have incorrect quality value.

Tier                      | Game | Website | Discrepancy
---                         | ---        | ---            | ---
Q1 Common      | +1%    | +1%        |
Q1 Uncommon | +1.3% | +1%        |x
Q1 Rare              | +1.6% | +1%        |x
Q1 Epic               | +1.9% | +1%        |x
Q1 Legendary   | +2.5% | +2%        |x
Q1 Common      | +2%    | +2%        |
Q2 Uncommon | +2.6% | +2%        |x
Q2 Rare              | +3.2% | +3%        |x
Q2 Epic               | +3.8% | +3%        |x
Q2 Legendary   | +5%    | +5%        |
Q3 Common      | +2.5% | +2.5%    |
Q3 Uncommon | +3.2% | +3%        |x
Q3 Rare              | +4%    | +4%        |
Q3 Epic               | +4.7% | +4%        |x
Q3 Legendary   | +6.2% | +6%        |x

![Quality module 1 quality modifiers for different quality levels.](https://github.com/user-attachments/assets/0861c916-1071-4849-888b-eac3e1c8be5c)
![Quality module 2 quality modifiers for different quality levels.](https://github.com/user-attachments/assets/966a8adc-6931-4ec8-b9b3-246b17bbebb7)
![Quality module 3 quality modifiers for different quality levels.](https://github.com/user-attachments/assets/fc24bd85-3f12-4e45-9524-0c930a877e82)

This is not only a visual glitch as the quality value of e.g. a recycler with 4 rare Quality modules 2 gets calculated incorrectly:
![Screenshot of a recycler's stats in game showing +8.3% quality.](https://github.com/user-attachments/assets/c89fa409-43f5-4926-95d9-9ea1ea1ebc79)
![Screenshot of the same setup on the website.](https://github.com/user-attachments/assets/74bca458-b5ef-4b2f-8c25-ecaf47667072)
![Screenshot of a recycler's stats on the website showing +7.5% quality.](https://github.com/user-attachments/assets/106047ea-3643-419e-86f1-783eeae0aa2c)
Notice how the difference is exactly 0.8%, 4x the discrepancy in the quality value for the Quality module 2.

**Comment by dcbroad3** [comment]
I don't understand how this could go unreported for so long, but it looks like this is a bug that has always existed in the quality code; it rounds down all bonus percents explicitly. I have a hard time believing that code was added completely for no reason, but it should be easy to fix.
