### ISSUE TITLE
enable recipes via tech tree

### ISSUE THREAD

**Issue by bbarry** [factoriolab/factoriolab#347]
It would be nice if there was a way to bring up a tech tree for a mod set and allow recipes to be enabled per researched technologies.

Particularly for seablock and BA mods there are many recipes that are unavailable in the first hundred hours or so and it is difficult to identify which recipes should be enabled or disabled on the dropdown.

**Comment by dcbroad3** [comment]
Thanks for the suggestion! This would require some major effort to implement, as the Lua scraper would need to be adjusted to pull all this information into JSON, then it would have to be somehow integrated into the app. I would guess that the best way would be to have options in the enable/disable recipes to enable/disable certain techs (and hence their associated recipes). I'll keep this on the backlog as a possible future enhancement, but it's not something I'm likely to be able to add anytime soon.
