### ISSUE TITLE
Add timeframe “Craft once”

### ISSUE THREAD

**Issue by ickputzdirwech** [factoriolab/factoriolab#444]
In addition to per hour/minute/second I suggest a forth option called something like “Craft once”.

The specialty about this option would be that every step would be rounded up to the  next item. There would of course only be significant difference to the other options if you use productivity modules.

Lately I wanted to know how much ore I would have to mine for things I only wanted to craft once. Since I can’t craft partial items and the last portion of productivity bonus gets lost the actual numbers can be significantly higher than the exact unrounded numbers.

**Comment by dcbroad3** [comment]
This calculator is intended more for continuous production of items. I would be willing to try to accommodate this request, but I believe it would require a completely separate set of logic to calculate - effectively an entirely new calculation engine separate from the current engine. I don't think this calculator is the right place to solve that problem.

**Comment by dcbroad3** [comment]
I want to think about this some more, reopening.

**Comment by dcbroad3** [comment]
I don't think this will ever be implemented, since it is a completely different type of calculation.
