### ISSUE TITLE
Add a "print display mode"

### ISSUE THREAD

**Issue by madmaxoft** [factoriolab/factoriolab#629]
**Is your feature request related to a problem? Please describe.**
I'd like to print the results on physical paper. However, it is rather difficult to do so efficiently right now:
- The background is dark, eating a lot of printer ink and making the printed text difficult to read
- There are sections on the page that don't need printing: the header, the inputs, the footers

**Describe the solution you'd like**
- Option 1: Add a checkbox for "light mode" and at least a collapse-button on the inputs
- Option 2: Add an "export for print" button that will generate a printer-friendly page, either HTML or (wow, fancy) a PDF.

**Describe alternatives you've considered**
I've tried saving the page locally and editing the HTML, that doesn't work, images are missing.
I've tried doing some in-browser manipulation on the HTML, but too many elements would need re-styling, which is manually not feasible.
I've tried selecting the results and copy-pasting them into LibreOffice Writer, this results in total garbage.

**Comment by dcbroad3** [comment]
As a short term partial solution, you can export the list of steps to a CSV using the button on the far right of the column headers. That doesn't include icons or any sugar, but it does have the basic numbers. 

The Kirk McDonald Factorio Calculator does also have this feature. 

I'll look into adding this to FactorioLab at some point.

**Comment by dcbroad3** [comment]
closed by #812

**Comment by madmaxoft** [comment]
Looks awesome, thank you.
