### ISSUE TITLE
Intermediate Ingredient w/ Multiple Configurations

### ISSUE THREAD

**Issue by pumrum** [factoriolab/factoriolab#630]
When working with a complex recipe, such as 360 follower count per minute, there are many intermediate items that are automated as part of multiple recipes. For example, Engines are built as an ingredient for both Blue Science and Electric Engines. It would be nice to be able to configure the factories for each recipe individually. I may use productivity modules when building engines for Blue Science, but speed modules when building them for Electric Engines.

**Comment by dcbroad3** [comment]
FYI, I think this would be automatically solved by #556, which I do plan to do eventually. Part of this is simple, but the app really isn't set up to handle different settings for the same items and recipes; that's going to require a pretty major refactor of everything.

**Comment by dcbroad3** [comment]
I think this is effectively solved by the way objectives work now when using machines as the units. When you do so, each objective allows specifying different settings. While this does not directly allow you to use different settings for the amount of machines required to feed into other steps, it does allow setting up multiple independent configurations with different numbers of factories for each configuration. I would consider this 'good enough'.
