### ISSUE TITLE
Create an item from a limited supply of one ingredient (eg: factorio fuel cells)

### ISSUE THREAD

**Issue by AartBluestoke** [factoriolab/factoriolab#633]
**Is your feature request related to a problem? Please describe.**
I am trying to make uranium fuel cells, taking into account recycling.
I would like to say 'make 18 uranium fuel cells from exactly 18 depleted uranium fuel cells, and as much fresh uranium and other ingredients as needed'

**Describe the solution you'd like**
I would like to be able to force a single extra recipe into the solution, even when that ingredient is not typically on the 'x items of y' list : 'using 18x fuel cell recycling'

**Describe alternatives you've considered**
The only work around at the moment is to have two tabs, one with recycling enabled, forcing inputs of the recycled cells, and the other with the recipe disabled, making what is left from the rest. you then have to manually adjust the sum of the two tabs to ensure the total produced is what you want.

**Additional context**
18 fuel cells is how many get burnt in an hour by an unmodded nuke reactor.
discussion as per https://discord.com/channels/806885678201831424/807737358556463107/901993817731915826

**Comment by dcbroad3** [comment]
I believe this is solved by the producers feature, let me know if I'm wrong.
