### ISSUE TITLE
Request support for 248k Mod

### ISSUE THREAD

**Issue by zelmak** [factoriolab/factoriolab#705]
**Have you checked whether this mod or set of mods has already been requested?**
[Check here](https://github.com/factoriolab/factorio-lab/issues?q=is%3Aopen+is%3Aissue+label%3A%22mod+support%22)
If you find the mod you're looking for, add a "thumbs-up" reaction or a comment to the issue.
Yes; currently not requested.

**What mod set are you requesting?**
248k Mod

**Is this mod set compatible with the latest version of Factorio?"
Yes.

**What mods are included in this mod set?**
It's standalone, but can work with IR2, K2, and SE

**Comment by Px05119** [comment]
Second this mod, thanks KoS for introducing me to it!

If I sub to this thread, will there be a notification when support is added?
