### ISSUE TITLE
Mod set request -> Krastorio 2 + Space exploration + 248k mod

### ISSUE THREAD

**Issue by Valoneu** [factoriolab/factoriolab#740]
**Have you checked whether this mod or set of mods has already been requested?**
Yes

**What mod set are you requesting?**
Krastorio 2 + Space exploration + 248k mod

**Is this mod set compatible with the latest version of Factorio?"
Yes

**What mods are included in this mod set?**
nothing more gamechanging

**Comment by dcbroad3** [comment]
Man, everyone taking about 248k lately.
#737 will make this a lot easier, I should be able to generate these data sets quickly once I make a few minor updates to the calculator.

**Comment by Valoneu** [comment]
https://www.youtube.com/watch?v=5W4VA_7VjJg this is why i think. and thanks.

**Comment by Valoneu** [comment]
atleast thats why i even want to play it

**Comment by Valoneu** [comment]
i forgot about AII industry you need to have that for SE
