### ISSUE TITLE
Productivity modules shouldn't apply to water in Krastorio enriched ore recipe

### ISSUE THREAD

**Issue by Mqrius** [factoriolab/factoriolab#743]
**Describe the bug**
When enriching ore in Krastorio, you can use productivity modules on the chemical plant to produce extra output. However, this does _not_ make it output extra dirty water; you get the same amount of dirty water as output as you put in clean water. Factoriolab incorrectly states that you get more dirty water out than you put clean water in. (If you would then filter the dirty water, you'd end up with more water than you started.)

**To Reproduce**
See [this recipe](https://factoriolab.github.io/list?z=eJxNk8dy4mgAhN-Gg6rsQib6iKQ.J0k2DHChwIHgWTzjPD58z76aPW33pUP1sX8V02wwzrJy2tv53lGcsw7yZaNmf0UjN3GU5Zu0-Ova.aacZnnvpT5l2Y6OWX9Tll1Bx95jnmV5Nt9Um3oz21z3Xjs3ojAUlsJRBIo5xYJiSXFHcU.xQHlBeUmZUw4pC8qKUlA2VHOqJdWR6kz1TPWO6CNyxBVigBCIFWKN2CI-EV-IP4hv5AXyEtlH5sgr5AA5RI6QE-QUeY30yIi8Rc6RC-QP5BK5Qq6RW-Rv5BvyC.kH-Y2aoQpUiapQAiVRCqVRBmVRDuVRAdWglqg79AX6Ej1AD9Ej9Bg9QU.R12iNDuiEbtG36BX6Eb1HH9D.YPqYHHOFGWBmmAJTYiqMwEiMw3hMwERMjdlh7jEPmBPmJ6abnzHP2D42x06wBdZja2yLXWO32B32DnuPfcDusQfsEXvCPmF.Ys.Ybv6FG-JGuDFugnvCnXHPuF-437gX3DvuA.eJH-JH-DE-4CM-4Wv8Ar.GH.GfhAFhRJgSHMETAiESbglzwoLwg7AkrAhrwpawI9wRDoQT8ZI4Jk6IFVERb4lL4oF4JHbtC.GV-EZ8J34QP0kzUkEqSRVJkCRJkTTJkCzJkTwpkCJpQVqRdqQH0oF0Jr1R96lvqOfUj9R76hP1E3WXf9NMaBRNS.NK805b0QpaSatoF7Rb2j3tgZuam4av7L-v.A.T3sfgX2gPLnU_) for example.

If you build this in the game, the predicted enriched ore output is correct, but the extra dirty water is never generated. Upon completion of the purple productivity bar, only enriched ore is outputted, not dirty water.

**Notes**
I don't know if the 3 enriched ores are the only recipes with this problem. There might be more.

**Comment by dcbroad3** [comment]
Thanks for pointing this out! I'll have to look into it. I'm guessing the calculator is not properly accounting for products that are catalysts.
