### ISSUE TITLE
Crash when loading the recipe tree

### ISSUE THREAD

**Issue by Valoneu** [factoriolab/factoriolab#752]
![image](https://user-images.githubusercontent.com/60077591/172462211-3fd54afc-7c7d-443a-82ea-002bb977729a.png)
loaded SE +K2 and clicked on space science again

_Originally posted by @Valoneu in https://github.com/factoriolab/factoriolab/issues/749#issuecomment-1149057454_

**Comment by dcbroad3** [comment]
Could you share a link?
I definitely see problems in the K2+SE icons already, working on it, but don't see this error.

**Comment by Valoneu** [comment]
sure https://factoriolab.github.io/staging/list?p=se-rocket-science-pack*60&s=kr2sxp&v=4

**Comment by Valoneu** [comment]
oke thanks
