### ISSUE TITLE
How hard is it to add a new game?

### ISSUE THREAD

**Issue by ncksol** [factoriolab/factoriolab#753]
So there is a new game in the class of "Factorio-likes" called Captain of Industry. I have already used Excel not once to calculate ratios of items production. It makes me long for a proper calculator I am so used to in Factorio, DSP, Satisfactory.

I was wondering how hard is it to add new game to the current calculator? Is there any kind of documentation on how this was done for DSP and Satisfactory? I'd probably like to take a swing at that.

**Comment by dcbroad3** [comment]
Two factors that determine the effort level:

- How good is the documentation for the game, is it easy enough to get all the icons, item, and recipe info from a wiki of some kind. I have a tool to generate data for Factorio but not for others. 
- How many actual customizations to the app are required, if the game has unique mechanics. For Dyson Sphere Program there were a fair number, for Satisfactory almost no changes were needed.

**Comment by dcbroad3** [comment]
https://github.com/Atakku/mekanism-lab

This is a fork I noticed recently that adds a new game based on a mod of Minecraft, looking at their commits might give you a decent idea of the work required. I haven't tried actually running the fork but it looked mostly complete.

**Comment by bugsybuilder** [comment]
I was on here trying to do the exact same thing. As far as getting the recipes parsed, someone has already done the major legwork.  https://github.com/brct-james/captain-of-industry-recipe-parser I imagine this will be one of the easier games to implement as there are no special productivity bonuses or anything, just a lot of recursive recipes which may make it a lot more computationally intensive. As far as customizations go, there are a couple of extra types of "power" that each machine uses. (electricity, workers, maintenance I II & III. computing) Farms may be a bit tricky as they are kind of inconsistent so maybe leave that for later. It is not to bad to do that step manually as it gives you an estimated average production in game. I would love to help contribute to making this a branch.

**Comment by dcbroad3** [comment]
I would be excited to add Captain of Industry support. I think the JSON file above could be converted into the FactorioLab format without too much difficulty, but an extra step would still be required to build a sprite sheet and the corresponding `icons` array in the data. 
Note: There is a new command in this repository, `npm run process-mod`, which can automatically calculate and add the `color` field to each icon, so if anyone is going to start on that, use that (or allow me) instead of trying to assign a color for each icon. 
If anyone can build a `data.json` and `icons.png` I can likely take it from there. If not, I will work on this at some point but do have some other items I'd like to get to first.

**Comment by copypasta1** [comment]
I hope this is a okay place to ask. I have been working on the data.json for Captain of Industry and I am looking for advice on how to make some products compatible with one belt and some the other belt? EX. In captain of industry iron ore is transported by U-Shaped Conveyor belts and Iron is transported by Flat Conveyor belts.

**Comment by dcbroad3** [comment]
@copypasta1 well, that's new. It's always something :)
I assume there is no overlap in the speeds of these belts? If they have equivalent speeds for both then it doesn't matter so much. To do that the right way would require code changes on my part, there is likely no way to do that right now. I would just create the different belts as is if you want to finish the data set, and force the user to pick the right belt in the ui for now. 
In the future, I could add a belts property to the item data to list which belts can transport the item. I'll have to change the calculator to support that as well. 
Right now the only distinction that could be leveraged is between fluids and items. Fluids use pipes for transport and items use belts. You could theoretically treat the ores as fluids but I don't think that's the best solution.

**Comment by copypasta1** [comment]
@dcbroad3 Well I think that problem does solve its self. The belts do have similar cost/speed so it would be just a UI issue. Thanks
