### ISSUE TITLE
cannot change beacon type in space exploration

### ISSUE THREAD

**Issue by SimonSchick** [factoriolab/factoriolab#756]
**Describe the bug**
In space exploration preset, cannot change beacon type.

**To Reproduce**
1. Go to [here](https://factoriolab.github.io/list?z=eJyFkEtTYjEQRv8Ni6zAGV9LyIsk9yaXt7q5JagIiqA4KC7Obxcpx8eUOvVVdaVz-uvq7oXWYqdaGRaVyVLUStnbBL9-CbuiVrmTcyFythI10eddClU28g-0lPotK.OTt.fWOeCTSmk.84-dNbqURtR.LLAX4uNfaeZv-WaU.EqIyEYb55C.2nrL1RaV-uG95N.m2eyVfU1vX2f.grVejWU-.b59PvzPct5-d.UX2vj98-2alz.yykWtVGUqs8qyKoS0yBayjewgu8geso8coKqoGmoHtUDdoZaoe9Qf1Ar1gHpErVFP6EO0Qg.QR-hj9An6CVPHNDAKEzAZJsdETMIUmBamjelgupgepo8ZYI4wY8wUu4fdxx5gD7ER28H2sQPsEfYYO8KeYc-xY5rXNGc0b3B1XAMncQqncQZncU2cw3lcgWvhrnEz3By3wFfxNfwv.B5-H3-Ar-M1vsC38Sf4U.wQP8Kf4c.xE.zGdYtf4R.wj.g1.omgCU2CIwRCQWgR-oQBYURWJdshq5M1yBRZQdYh65Jt0JS8SvTEQMyIp8QhcUQ8I54TL4hj4iVxQpwSr4jXxBnxhjgnLoi3xDviknhP8qRAykg5KZISqSC1SG1Sh9Ql9Uh9ijHFJcWEYkpxJYIQ4qCy2n0GwK9p7Q__)
2. Click on *any beacon type*
4. Beacon type does not change

**Expected behavior**
Beacon type should be changeable
**Screenshots**
Tried screen recording, didn't work tho :)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 102.0.5005.63

**Additional context**
None.

**Comment by dcbroad3** [comment]
Man, there just literally is no code block to handle changing the Beacon. I must have missed it when I did the code refactor a few weeks ago. I'll get that restored as soon as I can.

**Comment by SimonSchick** [comment]
Thanks!
