### ISSUE TITLE
Support Reforming Refine recipe in DSP

### ISSUE THREAD

**Issue by KenCoder** [factoriolab/factoriolab#761]
DSP added a new recipe, "Reforming Refine" for the refinery. Would be nice to support that in factoriolab.

**Comment by dcbroad3** [comment]
Could you share a link or image with the details of that recipe? I see it mentioned in the patch notes but I can't see it called out in the dsp wiki.

**Comment by KenCoder** [comment]
![2022-06-11 08_32_32-Dyson Sphere Program](https://user-images.githubusercontent.com/403709/173192230-5b56a72d-7341-48b2-99dd-23f1a068aed5.png)
Here you go

**Comment by dcbroad3** [comment]
You're awesome. Unlike the other recipe changes this will require a new icon in the sprite sheet so I won't be able to add this as quickly, but thanks for the info.
I assume proliferator with extra products only multiples the net output (1) not the gross output (3)? It's ok if you don't know.

**Comment by Mechtroid** [comment]
This recipe actually can't multiply extra products, only speed up the process. Same as X-Ray refining.  (Apologies for the duplicate issue, I must be blind.)
