### ISSUE TITLE
Missing Dyson Sphere Program recipe 

### ISSUE THREAD

**Issue by Mechtroid** [factoriolab/factoriolab#764]
DSP has added a single new recipe, adding yet another loop to the oil production.  
![image](https://user-images.githubusercontent.com/6485220/174192153-97749fa8-783b-4794-aa79-332ef6d61ebd.png)

**Comment by dcbroad3** [comment]
Thanks for the details! This is also logged as issue #761, so I'll close this one, but I hope to add the issue as soon as possible, probably by Monday or Tuesday.
