### ISSUE TITLE
DSP "Carbon Nanotube (advanced)" recipe incorrect

### ISSUE THREAD

**Issue by Mister-HACB** [factoriolab/factoriolab#765]
**Describe the bug**
Wrong amount of "Spiniform stalagmite cristal", calculator uses 2 instead of 6

Game Version:
0.9.26.12913

Calculator Version:
0.9.26.12891

**Screenshots**
![grafik](https://user-images.githubusercontent.com/54818612/174249907-e75bf29a-7b8a-42be-8017-4fb49ef4ec2e.png)
![grafik](https://user-images.githubusercontent.com/54818612/174249991-3a8fa3d0-9037-413a-893d-4e9857a2e9df.png)

**Comment by dcbroad3** [comment]
Can you share a link? This was fixed in the calculator a few days ago, I just rechecked it.

**Comment by Mister-HACB** [comment]
Ah it seems i used an old cached Version of the calculator.
Now it seems to be the correct recipe.
