### ISSUE TITLE
Weigh costs for Satisfactory resources per default

### ISSUE THREAD

**Issue by dtrauma** [factoriolab/factoriolab#788]
As the map of Satisfactory is handmade and finite, we know exactly how much of each resource is available, and can therefore give the cost of extractor recipes better weights than just 1000.

- iron:  1000
- copper:  2439
- limestone:  1331
- coal:  2278
- caterium:  6375
- quartz:  6703
- sulfur: 10289
- uranium: 33514
- bauxite:  7196
- sam: 13033
- oil:  6015
- nitrogen:  5865
- water: 1 or even 0

Additionally, we could give electricity usage a cost of 22.7 per MW (based on the resource cost of nuclear power, the most resource efficient power source according to this weight scheme). All numbers taken from the Satisfactory wiki.

**Comment by dcbroad3** [comment]
I like this idea. Weighting power usage is more difficult but maybe if I ever get around to treating power as a product

**Comment by dcbroad3** [comment]
Related: https://github.com/factoriolab/factoriolab/issues/404

**Comment by dtrauma** [comment]
It's not really necessary to treat power as a product, you could also just do (power usage for recipe in MW * 22.7) as the cost when you create the json file with all the recipes. Resource extraction would be the sum of power required and resource cost, then. That way you wouldn't have to filter the packaging recipes, too, as the LP algorithm would avoid pack/unpack loops due to power waste.

**Comment by dcbroad3** [comment]
Sure, that would probably work for Satisfactory. For Factorio, energy consumption depends on your setup, so it would need to calculate at runtime.

**Comment by dtrauma** [comment]
Nifty! I still think adding the power costs would be good, unless you have plans to handle them more generally across games in the near future? I could drop you a PR with the costs if you are interested.
