### ISSUE TITLE
Item picker not showing all tabs

### ISSUE THREAD

**Issue by alexbarrett** [factoriolab/factoriolab#798]
The item picker only shows a maximum of 6 tabs; additional tabs are hidden and not clickable. I noticed this when using the Nullius mod set which has 11 tabs.

![image](https://user-images.githubusercontent.com/114549/179969235-cba24f07-72fa-4561-aaf5-80cc23e803bf.png)

I was able to make the additional tabs show by adding `flex-flow: wrap` to the tabs element:

![image](https://user-images.githubusercontent.com/114549/179969291-337e2fc9-764e-43b4-8203-7c6a49e59053.png)

**Comment by dcbroad3** [comment]
That area is supposed to be horizontally scrollable. Is that chrome?

**Comment by alexbarrett** [comment]
Ah, I can confirm now that the area is horizontally scrollable. I am using Chrome on macOS with a scrollwheel mouse.

What has happened is:

1. macOS only shows scrollbars while scrolling. Without scrolling there is no indication that the area is scrollable.
2. macOS users typically use devices with gesture support (touchpad or apple magic mouse) and "discover" scrollable areas by swiping.
3. Because I'm using a scrollwheel mouse, I did try using my scrollwheel on the area but this does vertical scrolling not horizontal scrolling. Now that you've pointed it out I know to scroll the area by using shift+mousewheel instead of just mousewheel.

So this is a combination of poor macOS UX & my use of a scrollwheel mouse. Ideas that I can think of from here:

* Respond to mousewheel scroll events without the shift modifier.
* Indicate that there are additional, hidden tabs somehow (arrow / ellipsis / partially visible tab).

But perhaps this issue can be ignored because my set up is probably uncommon.
