### ISSUE TITLE
DSP creating empty accumulators by discharging full ones

### ISSUE THREAD

**Issue by lordyoyo** [factoriolab/factoriolab#814]
Is it possible to add the inverse recipe of the one that creates full accumulators, via the Energy Exchanger? I don't think it's super relevant in the context of the calculator, but it might just be useful for some things.

**Comment by dcbroad3** [comment]
This would be more relevant if power were treated as a product. That is an open request on the backlog that I intend to try to implement, but either way, yes this could be added.

**Comment by dcbroad3** [comment]
Closed in #843
