### ISSUE TITLE
Implementation of web workers

### ISSUE THREAD

**Issue by kangzoel** [factoriolab/factoriolab#826]
Firstly I'd like to thank you for the developers making this amazing tools. I found this tool is really helpful for my vanilla playthrough.

However, I found that the calculator isn't optimized in terms of performance. This is caused by the calculations. The current approach is to calculate the rates on UI thread. So, when I change a number, the UI will be frozen till the calculation is completed. I think this is a bad UX.

I recommend moving the calculation to a separate thread (i.e web worker) so that no UI freeze will ever occur.
Adding input debounce will also helps the UX, so the calculator begins calculating only when the user completed typing.

**Comment by dcbroad3** [comment]
I also have a new branch which will only recalculate on blur for most (maybe all) input fields

**Comment by kangzoel** [comment]
> While I do definitely want to investigate using workers, it's been on my mind for a while now, I think you may be overestimating the effect on performance. I've spent a lot of time lately looking at performance logs, and it seems to me that almost all of the lag comes from actually rendering the results, not calculating.
> 
> Either way, I agree that the calculations should be moved to workers, even if it doesn't make a huge difference.

Ah, I see. I have no experience in angular, so I don't know how to debug the performance. I'm sorry for making such speculation. 


> I also have a new branch which will only recalculate on blur for most (maybe all) input fields

I'll gladly check it out 😁

**Comment by dcbroad3** [comment]
I wouldn't mark this as completed! I still plan to investigate using workers at some point.

**Comment by kangzoel** [comment]
Sorry, my bad. 

Hi, I have checked the next version. I found that the performance is better than the current version. Great job!
However, May I suggest to debounce the input instead of doing action on blur? I think it's more intuitive

**Comment by dcbroad3** [comment]
I can look into that, yes. You're probably right that it could be confusing if you enter a new number and wait but the calculator never updates

**Comment by dcbroad3** [comment]
With the use of `glpk-ts`, I think there's little need to offload any calculations. There shouldn't be any large calculations that would make sense to offload moving forward.
