### ISSUE TITLE
VeryBZ

### ISSUE THREAD

**Issue by T1nyTim** [factoriolab/factoriolab#844]
**Have you checked whether this mod or set of mods has already been requested?**
Yes

**What mod set are you requesting?**
VeryBZ

**Is this mod set compatible with the latest version of Factorio?"
Yes

**What mods are included in this mod set?**
It's a modpack of BZ mods, made by the creator itself. However, they also have Tin, which isn't part of the pack. So don't know if you'd therefore want 2 sets.

**Comment by aeosynth** [comment]
-1 for tin:

https://mods.factorio.com/mod/bzvery
> Future BZ mods will be added to this mod pack, once they are out of the "alpha" phase.
