### ISSUE TITLE
Old flow style in new UI

### ISSUE THREAD

**Issue by shadoxxhd** [factoriolab/factoriolab#845]
**Is your feature request related to a problem? Please describe.**
I greatly prefer the old flow visualization over the new one.

**Describe the solution you'd like**
I'd like some option to switch which flow visualization should be rendered.

**Comment by shadoxxhd** [comment]
Would https://github.com/ricklupton/d3-sankey-diagram be a suitable replacement? Doesn't have recent updates either, but at least an NPM release...

**Comment by dcbroad3** [comment]
That one also looks pretty dead, and it also doesn't seem to be designed to handle circular links, which was why d3-circular-sankey was necessary in the first place.

**Comment by dcbroad3** [comment]
I could give it a try. It doesn't appear to be any better maintained than d3-circular-sankey, but it's possible it's still in better shape.

**Comment by shadoxxhd** [comment]
The live demo doesn't look too bad, considering the render space is extremely limited in that demo:
![image](https://user-images.githubusercontent.com/6153557/192001838-2ad9ecc1-5b7b-4178-b9c7-e15d778a4de1.png)

With proper spacing, it should look somewhat similar to the previous renderer.

**Comment by NJAldwin** [comment]
@dcbroad3 I'll join others in wishing for a sankey option again!  However, there are a few tweaks to the current graph generation that might make it easier to use in the meantime:
- would it be possible to color the nodes/edges by item, similar to the sankey example?  Right now, the two-tone colors look slick, but they become quickly unusable with even moderately complex factories
- similarly, the ability to change the edge text/width based on # of belts/factories would be super helpful in attempting to decipher the graphs
- preserving the graph view when switching tabs would be extremely helpful.  I'll often move around nodes so I can get a clearer picture, but if I switch to another tab to check the factory details, when I switch back to the graph, it has reset to its default positioning
