### ISSUE TITLE
"Space Exploration"

### ISSUE THREAD

**Issue by JaredCR83** [factoriolab/factoriolab#849]
**Interested in contributing?**
Use [FactorioLab Export](https://mods.factorio.com/mod/factoriolab-export) ([Source/README](https://github.com/factoriolab/factoriolab-export)) to export the mod set yourself, fork this repository, and create a pull request!

**Have you checked whether this mod or set of mods has already been requested?**
[Check here](https://github.com/factoriolab/factoriolab/issues?q=is%3Aopen+is%3Aissue+label%3A%22mod+support%22)
If you find the mod you're looking for, add a "thumbs-up" reaction or a comment to the issue.

**What mod set are you requesting?**
E.G. "Bobs and Angels", "Pyanodons", "Seablock", etc.

**Is this mod set compatible with the latest version of Factorio?"
Yes or no. If no, please list the last version that it is compatible with.

**What mods are included in this mod set?**
E.G. list all the distinct mods that should be included from the mod portal.

**Comment by dcbroad3** [comment]
Could you elaborate? Space Exploration is already a supported data set.

**Comment by dcbroad3** [comment]
Closing, if you can elaborate on what you are requesting I'm willing to reopen the issue.
