### ISSUE TITLE
Scrolling with dropdown open moves dropdown

### ISSUE THREAD

**Issue by beeryt** [factoriolab/factoriolab#862]
**Describe the bug**

**To Reproduce**
1. Open *Settings* sidebar
2. Open drop down (such as *Chemical fuel*)
3. Scroll the main window
4. Observe the dropdown menu dislocate from the *Settings* sidebar

**Expected behavior**
The dropdown menu should follow/track the *Settings* sidebar.

**Screenshots**
![image](https://user-images.githubusercontent.com/14947602/198470196-7d69cdf5-4bce-4be6-b621-e4e015a25c89.png)

**Desktop (please complete the following information):**
 - FactorioLab 2.0.52 (next)
 - OS: Windows 10
 - Browser: Chrome 106.0.5249.120

**Smartphone (please complete the following information):**
 - FactorioLab 2.0.52 (next)
 - OS: Android 11
 - Browser: Chrome 106.0.5249.126

**Additional context**

**Comment by dcbroad3** [comment]
Opened an issue in PrimeNG for this, as it *appears* to be a bug in PrimeNG itself:
https://github.com/primefaces/primeng/issues/12114
