### ISSUE TITLE
Putting in Several Products Causes Order to Mix

### ISSUE THREAD

**Issue by MuppetMurderer** [factoriolab/factoriolab#874]
When putting in several products, at least for DSP, the order in the tree tends to get mixed around. In the image below, the iron, circuit boards, magnetic coil, gears, iron ore, copper ingots, and copper ore were all at the top, even though I had several other steps before that that used them.
![Order Mismatch](https://user-images.githubusercontent.com/115334462/202080476-61878a93-768c-410e-b35a-8ed0354f6951.png)

A couple things that may have caused this were that I had a total of 27 products, which may have caused lag when forming the tree, and that I was using the DSP calculator.

Recreation Procedure: Put in a large amount of products in the DSP calculator, then view the tree. If it's something to do with the specific product list that I had, then this is the list I had: 
![Product List](https://user-images.githubusercontent.com/115334462/202081738-1f4a3c8d-6551-425d-b8c8-327d06d58eb2.png)

**Comment by MuppetMurderer** [comment]
I just realized that I'm just stupid, and the new site has a different order system.

**Comment by dcbroad3** [comment]
I don't think the sorting algorithm has been changed, could you share an example?
