### ISSUE TITLE
K2 / K2+SE matter

### ISSUE THREAD

**Issue by Valoneu** [factoriolab/factoriolab#881]
**Is your feature request related to a problem? Please describe.**
When i want to have matter based factory i need to produce the matter from smthing so the ore numbers get inflated and i dont want that

**Describe the solution you'd like**
I would like to have there a matter from nothing recipe so i can just see how much i need it without it inflating the ore rates

**Comment by Valoneu** [comment]
yes i think it did

**Comment by Valoneu** [comment]
Also can i somehow toggle so it dont look like tree only the amount of items i need not for what

**Comment by Valoneu** [comment]
also i did found out the calculator doesent make oil cracking the right way

**Comment by Valoneu** [comment]
![image](https://user-images.githubusercontent.com/60077591/205397810-25e12347-9a7e-4adf-b604-b7e89d040f5a.png)
this is the oil cracking it doesent balance it

**Comment by dcbroad3** [comment]
> ![image](https://user-images.githubusercontent.com/60077591/205397810-25e12347-9a7e-4adf-b604-b7e89d040f5a.png) this is the oil cracking it doesent balance it

Could you share a link to that?
If you ignored matter as an item then it assumes matter is free, which means it will prefer generating directly from matter rather than cracking (which uses water which is not free, unless it's also ignored)
Other things that it could be: cracking recipes are ignored, or if water is also ignored, it may be cheaper in terms of number of factories to directly produce petrol from matter.

**Comment by Valoneu** [comment]
https://factoriolab.github.io/next/list?z=eJxNkstu6jAQQP-GRaRW0DbQLmtCHiZJSWwKZoMC5ZG20AcEelmcb78EVU1s6czxzGjshT.Xlt2c9t4vPJYUvZJhUjIel3RXJZ90SXXJy0sxLultSvpeyeCqZL9bUl.yweDMxixs5L0vq9X4HncsK-Oyp2ZUuXit3GvX8m-Vd28qd9c1n9Vmvvx5eVrVKsPa1KfKZbfWoyof124zt5VHeeXJQ-VOsza.qPWcam5X7m9rHtR6lpXHWe0N4z9vLFtWSma1rMxypomVljZVv.HRulSm6e958RvzqZCN3fmVIkBIRB8RITRiiBghxog54gWxQJzotugmODnOBmdLz9DLcK9xm7g3uDbuPe4D7h7PxfPwAjyJF-IleGN8Hz.F1.gbggnBjOAL2UQ-IVPkBJkhZ8g58gW5QC6RK-QamSNfkW.Id-QGuUV-IAv6W.of9D.pfxHeEdqEbcKcsCA8EmmiIdEz0ZjIEE2IMqIZ0Zy4Tdwh.ibeEe-JC-ID8ZFBk8GKwSuDE0mHRJB4JAnJjqQgdUh7pC6pR.pMOiHNUFeoa1QT1ULdoG5Rdygb1UZ1UPeoB9Qj6hu1Q-1RBeqAOqJ-UP9QJ.QjWqC7aAfdQ7toD-2jA7REjxh9MPrE2JgOxmAyzAwzxywwS8wak2N2mD2mwBwwR8wPa8s57-LOcs7.6G-1Ggf7P2ZdWTU_

**Comment by Valoneu** [comment]
why would it assume water is not free when it is, and it takes like 1 min to load

**Comment by Valoneu** [comment]
if i create water from matter that fixes it

**Comment by dcbroad3** [comment]
I must be missing something; when I open your link, I can see that it's using cracking.

**Comment by Valoneu** [comment]
oh when i change smthing does the link stay same?

**Comment by Valoneu** [comment]
because i changed a bit of things

**Comment by dcbroad3** [comment]
> oh when i change smthing does the link stay same?

The link contains the state, if you change something after creating the link it won't change what the link does

**Comment by dcbroad3** [comment]
Is there still an issue here? As far as I can tell so far the calculator is behaving as expected.
