### ISSUE TITLE
Calculation data error

### ISSUE THREAD

**Issue by happymy** [factoriolab/factoriolab#895]
in satisfactory update 7
https://github.com/factoriolab/factoriolab/issues/885
The nuclear reactor consumes 600 water per minute at 250% overclock.
6x600=3600
NOT 4500 in
https://factoriolab.github.io/next/list?z=eJwrcMrUMtAzN1VLClMrckrRAgNDA4N4pygE2xDB9EAwXRBMLyR9JVpazmppEC1GpiAdzjBmAFChs1oxkOeqBQPuamWmAKLkHNA_

**Please** recheck the recipe and the amount of fuel and cooling water consumed by each type of generator.
The are may change in update 7.

**Comment by dcbroad3** [comment]
Will do

**Comment by dcbroad3** [comment]
Closed by #898
