### ISSUE TITLE
Loading an URI does reset to empty page (next)

### ISSUE THREAD

**Issue by Zocker1999NET** [factoriolab/factoriolab#897]
**Describe the bug**
When loading an URI, which (should) encode all configured settings & objectives, the page just resets to an empty state instead of loading the expected calculations.

This happens when reloading the current page or using the "open in new tab" button or when loading an stored/sent URI like [this one](https://factoriolab.github.io/next/list?z=eJwdySsPwzAQA-B.c8Aop2rlTa1pI1VB-YE-sxVM2gPeb18S4E-W.RrQBovfaijOhb7OnGqvZ.9BE4KkuEDtzIlrhteMQmVTlN-i3ewub4Cbc3cezuR8OJ.O00dP6ED5Xf6VGyH-).

**To Reproduce**
1. Configure some settings as you like
2. Configure any objective
3. Scroll down to a sub-objective (e.g. for "Iron Plates", one would be "Iron Ore")
4. Click on the "open in new tab" button for that sub-objective
5. Observe an empty page.

**Expected behavior**
Load the calculator with the same settings and the selected sub-objective inserted.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux
 - Browser: Firefox 106.0.5 (64-bit) / Chromium 107.0.5304.121
 - FactorioLab 2.0.62 (next)

**Additional context**
I'm really happy with this calculator, thanks for your work.

**Comment by dcbroad3** [comment]
I just fixed this bug a day or two ago, not sure why it seems to be happening again. I'll likely work on this tomorrow.

**Comment by dcbroad3** [comment]
Closed by #898

**Comment by Zocker1999NET** [comment]
Thanks, works again :+1:
