### ISSUE TITLE
It doesent want to choose the alternative recipe even tho it should

### ISSUE THREAD

**Issue by Valoneu** [factoriolab/factoriolab#913]
(https://discord.com/channels/139677590393716737/175392066820505600/1053734585483133058)
Opera GX, latest version

**Comment by dcbroad3** [comment]
Ignore the inputs to the copper ore from matter recipe, and it calculates just fine. It just can't find a way to produce the required inputs to the matter recipe.
![image](https://user-images.githubusercontent.com/8430702/208440498-bf95a456-4ef0-4dde-b8d0-b7b5760a49ee.png)
https://factoriolab.github.io/list?z=eJwlyFtv2kAYhOF.w8VKieyqlPQyi722P7BhFwfb3FicDw1JKEmIcvH-9rJUIz0zmred6gZt.Hzz4tWxd2i9Re01W--o9E5uv3iSozdNvNmdd9D3lrc.G1.tLIad.WiqwrZcXYlPKuxsQuWYq1DNVdRa5Ufr.tdauVvvWy3tpN22m1av2sfOOVCqi87Qgh6gS.QTeoqu0DV6iV6h1-gv-iF9S7QneiUOiEPiC.E35h4TYH5gfmK6mAfMb8wJ805iSBKSjERILElNmpI60pJ0S7ojPZItyA5kJyRANDJEZsgcWSBLZIWskQ2yRXbIHjkgf5Bn5Ii8IK8MXhhcfWNwYrhneCEvyZ.Ip-Q1eUM-I5-TL8iXFL8oehR.Kc4U7xQfFJ8UF0ZTxgdsD5tgLfaM.cAFuAgX4wwuwU1xM9ycySOTMRNLWVHdUd1TPVD3qB9pejQVzZLmQvPFrM8sVdE1G6uirPPZ.QeFVrUL&v=5
