### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by Valoneu** [factoriolab/factoriolab#919]
**Describe the bug**
Basically there is more categories that it can display in the recipe selector

**To Reproduce**
get modpack with unsorted category
go to recipe settings and if u search something in the category thats next to it it appears cause some will dissapear

![image](https://user-images.githubusercontent.com/60077591/208777894-3708c0c8-8a63-4281-bcb1-e76e834332b0.png)
![image](https://user-images.githubusercontent.com/60077591/208777931-3a6f1d2c-1c32-44e1-a08f-3cf22ef70837.png)

**Comment by dcbroad3** [comment]
That is supposed to be scrollable, is it not? I tested using the largest data set (pyanodons + alien life) and the scroll seems to work fine

**Comment by Valoneu** [comment]
if its supposed to be on mouse wheel i cant scroll it

**Comment by dcbroad3** [comment]
It's just click and drag horizontal scroll

**Comment by Valoneu** [comment]
![image](https://user-images.githubusercontent.com/60077591/208827734-6a9a3bdb-71c1-4c28-80c8-ede675283899.png)
i cant but i can do this

**Comment by dcbroad3** [comment]
Did you say at some point you're using opera?

**Comment by Valoneu** [comment]
yes im using operaGX

**Comment by Valoneu** [comment]
also is the site broken it doesent want to load now only grey screen

**Comment by Valoneu** [comment]
happy christmas btw
