### ISSUE TITLE
Sorting recipes

### ISSUE THREAD

**Issue by Valoneu** [factoriolab/factoriolab#920]
**Is your feature request related to a problem? Please describe.**
When building reverse megabase its kinda hard in modpack with so many items

**Describe the solution you'd like**
Being able to sort recipes by End product -> most basic thing

**Comment by dcbroad3** [comment]
Likely a duplicate of #479?
I don't think there is a concrete 'order' of end product -> most basic thing that is quantifiable, so in a literal sense I'm not sure this request is feasible.
