### ISSUE TITLE
Gas Giant buttons invisible in "disable recipes" popup.

### ISSUE THREAD

**Issue by NelsonMinar** [factoriolab/factoriolab#922]
Thank you so much for your calculator! It's a great tool and has been for years now. One small bug in the UI that's been bothering me:

1. Go to [a factory recipe page](https://factoriolab.github.io/list?p=e-matrix*60&s=dsp&v=4) for Dyson Sphere Program.
2. Click on "14 optional recipes disabled"
3. Scroll the popup list of recipes to the bottom row
4. No icons appear for the gas giant recipes. The buttons work though.

Here's a screenshot with the rightmost button moused over to show that it works.

![firefox_F9nrME4g4H](https://user-images.githubusercontent.com/382136/209572561-6b1cafd5-b954-46e4-a557-f8d5fe5416d2.png)

I'm on Windows, bug shows in both Firefox and Chrome.

If you need to pick an icon I'd just use the picture of the product. Or maybe an Orbital Collector. Or somehow a mix of the two.

(While I'm here; it'd be nice if this popup were big enough to contain all the rows without needing to scroll. Also a title on the popup would make the UX more clear, maybe "Enabled Recipes" or something.)

**Comment by dcbroad3** [comment]
For what it's worth, this is mainly a style issue. If you use dark mode it should resolve this problem for you, but I do need to update the light theme (or the icons) to resolve this.

**Comment by NelsonMinar** [comment]
Thanks for the response and fix! Not sure it's complete though; the left 4 icons now show up in Light or System theme, but not the right two. They do work fine in the Dark theme. Screenshot below.

![Screenshot_1](https://user-images.githubusercontent.com/382136/210618625-578f7dca-1eb6-4a90-9e6b-ab2912247e9a.png)

**Comment by NelsonMinar** [comment]
I took a quick look at the CSS and I think these buttons are getting inverted now:
`<span class="p-button-icon lab-icon-sm recipe gas-giant-deuterium" aria-hidden="true"></span>`
but these aren't:
`<span class="p-button-icon lab-icon-sm recipe ice-giant" aria-hidden="true"></span>`

There's three different CSS classes for the ice-giant-* buttons that may not have been marked as needing inverting.

**Comment by dcbroad3** [comment]
Oops. Reopening.

**Comment by NelsonMinar** [comment]
Thanks, live site looks good now!
