### ISSUE TITLE
Provide old UI

### ISSUE THREAD

**Issue by NJAldwin** [factoriolab/factoriolab#928]
FactorioLab is great!  However, like many others, I greatly prefer the old UI -- colorized sankey diagrams, the ability to see factory setup counts at a glance, the diagram not resetting when switching tabs, etc, many things that haven't caught up in v2 yet.

I used to be able to switch to the old UI via an option, so that I could continue to productively use FactorioLab until the rewrite is complete.  Now, I can't find that option anymore.

Additionally, in #845, you noted:

> The existing version of FactorioLab at https://factoriolab.github.io/ will likely be moved to https://factoriolab.github.io/old

However, that link seems to just run the new UI still.

Until the new UI has feature parity with the old one, would you please consider making the old one available?

Alternatively, is there an old UI branch I could run locally?  I don't see one.  I'm a software guy myself, so I would be open to hosting a V1 UI myself if that would be allowed (I'm sure others would be interested as well)

**Comment by dcbroad3** [comment]
The only thing I'm aware of that is theoretically "behind" in V2 is that the Sankey diagram was removed. Could you elaborate on your other issues?

**Comment by NJAldwin** [comment]
Hey @dcbroad3 , thanks for the reply!

I think you're right that most of the "missing" features are related to the removal of the Sankey diagram.  However, there are a number of smaller changes to the graph that could be brought back without bringing back the Sankey diagram; I've listed several in my comment here: https://github.com/factoriolab/factoriolab/issues/845#issuecomment-1368499854

As far as the other issues, I know you have several listed in #921 as well, which is great to see, and I look forward to the improvements.

-----

My main interpretation is just that the old UI was so incredibly polished and a joy to use, and the new one isn't quite to that same level _yet_ :)

------

I just forked d3139bd (before #893 was merged) and ran it locally.  Here are some comparison screenshots of a smallish factory plan to demonstrate some of what I've been running into:

(note: I thought there used to be a way to change the Sankey to be vertical / change the overall widths/heights.  perhaps I am misremembering that from a similar tool -- but I could have sworn I used it a lot since I sometimes use a vertical second monitor while playing Factorio)

__production config__

<img width="786" alt="FactorioLab___Factorio_Calculator" src="https://user-images.githubusercontent.com/145036/210185187-72fb18fa-d003-4cf6-8aa3-873eb1dd1a0a.png">


<img width="1361" alt="Piercing_rounds_magazine___FactorioLab" src="https://user-images.githubusercontent.com/145036/210185247-45e2a69b-7338-4f0b-b82b-c229d158f47c.png">


as discussed elsewhere, the UI here is larger on screen than the old UI, but without more information; in fact, it has less:
- hovering over the item being produced shows stats about that item
- (not shown) hovering over the factory configs / belts shows information about the factory/belt
- the new UI doesn't expose the ability to configure per-item factory/belt in this section


__table__

<img width="1728" alt="FactorioLab___Factorio_Calculator" src="https://user-images.githubusercontent.com/145036/210185381-c635571a-f596-47ea-a011-b209645d9c45.png">
<img width="1728" alt="Piercing_rounds_magazine___FactorioLab" src="https://user-images.githubusercontent.com/145036/210185389-cbdbb515-f5ab-4012-b541-96083c9339f9.png">

- despite the text being _smaller_, the new UI fits much less on the screen.  note that in the old UI, the entire factory for this example fits on a single screen; in the new UI, it does not.


__chart__

I discussed most of my issues here in this other comment: https://github.com/factoriolab/factoriolab/issues/845#issuecomment-1368499854

I'll drop a couple of screenshots.  these are both zoomed out a bit using browser zoom.
<img width="1313" alt="FactorioLab___Factorio_Calculator" src="https://user-images.githubusercontent.com/145036/210185529-67879cb1-89bb-4774-b4e3-efce0a31d9de.png">

<img width="1491" alt="Piercing_rounds_magazine___FactorioLab" src="https://user-images.githubusercontent.com/145036/210185538-c9fe9ccd-e2c1-4ebb-b5ff-e5161f6b9b27.png">

- text size is fairly small for both graphs, but the old one is vastly easier to use at a glance due to:
    - color coding of nodes and edges -- this one is huge for me!  even for a small factory like this, the new three-tone graph is nearly impossible to read without spending some time dragging things around (the old one could be put up as-is on a second screen as a quick reference while building)
    - (Sankey diagram is just much easier to grok for this type of factory layout)
    - the ability to change widths and the text on them (e.g. belts)
    - the ability to select a node and view the factory for it right on the graph page (so that you don't have to change tabs / context switch and lose the graph customization)
- (not pictured) the scroll-to-zoom gets me _every time_ I open this tab 😭  since with the new UI's large screen real-estate, I have to be scrolling down constantly

----

I'm sure there's more that I've run into while trying to use the new UI, but these are just a few things off the top of my head :)

(these are all Factorio screenshots, but I've used FL for DSP in the past, so there may be some things unique to that as well)

I totally understand that with any new changes there will be an adjustment period, etc; similarly, I acknowledge that you're not working on the old UI and will be pulling all these features into the new UI.  I'm just hoping to be able to continue using the old UI until the new one has surpassed it in terms of usability :)

Since I was able to get the old UI running locally, I'll probably continue using that moving forward for now.  however, I'm sure there are others who would still be interested in the old UI as well.  If you were to statically host an old version somewhere, that could be useful.  As I mentioned above, I would also be interested in statically hosting the old UI; I just don't want to step on any toes (or claim ownership at all of your great tool)

**Comment by dcbroad3** [comment]
> hovering over the item being produced shows stats about that item

I'm not convinced the information in that context is as useful as a tooltip letting you know what the button will do (for new users). Considering it's just the machine information and you're picking it as an output product.. I could try to add this back in some form, but for many items there won't be anything to show here regardless.

> (not shown) hovering over the factory configs / belts shows information about the factory/belt
> the new UI doesn't expose the ability to configure per-item factory/belt in this section

Those settings were removed in favor of the producers feature. More often than not, this caused confusion as the settings in this section are completely separate from the settings in the list view. 

> despite the text being smaller, the new UI fits much less on the screen.

A common complaint. I will look into shrinking the padding throughout. Each row in the new version is 13% (6px) taller, for example, even though the contents are the same. This is a side effect of using a component library, most of which use liberal padding. The current 'next' branch uses the smallest possible padding out of all available base options, most options are actually significantly more padded.
