### ISSUE TITLE
Industrial Revolution 3

### ISSUE THREAD

**Issue by dwightkung** [factoriolab/factoriolab#956]
**Interested in contributing?**
Use [FactorioLab Export](https://mods.factorio.com/mod/factoriolab-export) ([Source/README](https://github.com/factoriolab/factoriolab-export)) to export the mod set yourself, fork this repository, and create a pull request!

**Have you checked whether this mod or set of mods has already been requested?**
[Check here](https://github.com/factoriolab/factoriolab/issues?q=is%3Aopen+is%3Aissue+label%3A%22mod+support%22)
If you find the mod you're looking for, add a "thumbs-up" reaction or a comment to the issue.

**What mod set are you requesting?**
[Industrial Revolution 3](https://mods.factorio.com/mod/IndustrialRevolution3)

**Is this mod set compatible with the latest version of Factorio?"
Yes.

**What mods are included in this mod set?**
Industrial Revolution 3 3.0.10
Industrial Revolution 3: Assets 1 >= 1.0.7
Industrial Revolution 3: Assets 2 >= 1.0.4
Industrial Revolution 3: Assets 3 >= 1.0.1
Industrial Revolution 3: Assets 4 >= 1.0.1

**Comment by dcbroad3** [comment]
This was added yesterday, is there a problem with the data set?

**Comment by dwightkung** [comment]
Nope, i did refresh the page just, i didnt see it, maybe network problem. thx for the update, you can close the issue.
