### ISSUE TITLE
Fatcorio-Space Exploration - Steel Calc Issue

### ISSUE THREAD

**Issue by descaloni-thinkwhy** [factoriolab/factoriolab#973]
This maybe a user error, but...
When setting the product to the steel plate, it is not showing the list item of the steel. As a result, I cannot change or set any settings for the factories on the steel
![Capture01312023](https://user-images.githubusercontent.com/53185870/215848781-1d158ede-e2ba-4be3-b896-76efb4b101ef.PNG)

**Comment by dcbroad3** [comment]
Can you share a link? My guess is the steel row is further down in the list, possibly under another item due to a recipe loop?

**Comment by descaloni-thinkwhy** [comment]
https://factoriolab.github.io/list?z=eJwr8E7TMtEy1HIqU0sKUEszjHeK94.3UStWKzMHAGoSB7g_&v=7

**Comment by dcbroad3** [comment]
Yeah, it's there, about halfway down the page. It feeds into another recipe which is why it's not at the very top

**Comment by descaloni-thinkwhy** [comment]
Got it, Thank you
