### ISSUE TITLE
Pyanodon crash

### ISSUE THREAD

**Issue by dengamu** [factoriolab/factoriolab#974]
**Describe the bug**
Attempting to narrow down technologies used in Pyanodon + AL, page crashes and shows "The application has encountered an error: TypeError: Cannot read properties of undefined (reading 'length')

**To Reproduce**
1. Go to 'https://factoriolab.github.io/list?z=eJwNykFPwjAcQPFvs8MSyJaYbNf9aacgGRRsZ7ksgq5KYipghHB4n90efnmX97N8yh.yMtt32VgO3dAMErNLkefllOqdOiAVolqkLZIb8lgj829k8YEst4lNeqRbI5sJ4k5In.63BRJT4y-zM6pBaXSH3qA9aTYFpsY8YyLmjLmyFV5a7AQ7xY7YT-wXrsEpnMa1-Aa.wjt8z0449BxeGYVRETrCirAmRI4zjjuuN-4n7pfsr.oH1jFSPw__&v=7' for error on demand.

To reproduce the behavior from a good state:
1. Go to 'https://factoriolab.github.io/list?z=eJwNystqwkAYQOG3ySKgJFBItvmdSdVKdLQz6bgJ3pJWKFO1VHFxnr2z-Dib87OYpi9pnuybpM-7pqs6CcktS9N8THGkHJACUTVSZ9EDeS2R2TcyPyGLTWSjFmlWyHqEuAvSxn83R0Js-GVyRVUojW7Qa7QnzibDlJg3TMBcMXc2wnuNHWHH2B77if3CVTiF07gaX-GXeIdv2QqHlsMHvdArhiXDiiFwnnDecn.wvPC8JX.FP-HBUQw_&v=7'
2. Find 'Raw borax'
3. Disable 'Raw borax and Niobium ore from Tar' recipe
5. See error

**Expected behavior**
Expect successful re-calculation and to continue to narrow recipes down.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Attempted on Edge 109 and Chrome 109

**Additional context**
This specific error has occurred multiple times with various recipe configurations, however, I have only attempted and encountered it with Pyanodon + AL (which is a major version behind live)

**Comment by dcbroad3** [comment]
It looks like this link no longer generates an error, now that the data for Pyanodons has been updated.
(Unfortunately, it just fails to find a solution now)

I checked out the previous version because there is still a bug here I'll address, it's just much more difficult to reproduce in the current version. Should have it fixed soon.
