### ISSUE TITLE
Display of required materials on lower level wrong

### ISSUE THREAD

**Issue by NeoVanAlemania** [factoriolab/factoriolab#976]
**Describe the bug**
Display of required materials is on the wrong level shown.
For e.g., Electromagnetic turbine in Dyson Sphere Program the almost below level are Iron Ingots which should be shown below Gears.
But the Iron Ingots are shown on first level instead. (see attached screenshot)
![Screenshot 2023-02-01 174359](https://user-images.githubusercontent.com/13784345/216106874-f00223b1-4819-4f4c-a013-eae4052b5d2f.png)

**To Reproduce**
1. Choose Dyson Sphere Program
2. Add a product -> Electromagnetic turbine
3. Display of required materials on lowest level is wrong. (e.g., Iron Ingots should be below Gear)

**Expected behavior**
See attached screenshot

**Screenshots**
See attached screenshot

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome, Edge
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by dcbroad3** [comment]
This is the intended behavior. If an item feeds into multiple steps, then it is moved to the root of the list, because it is not currently allowed to duplicate the row twice in the table.

**Comment by NeoVanAlemania** [comment]
Tbh, that doesn't make much sense how the current system works.
If I want to produce a specific part I only want to know how many parts I need for this chain.
Why just not show the parts as shown in the screenshot?

**Comment by dcbroad3** [comment]
The calculator currently assumes you will centralize all production of a given item, instead of producing only what you need to feed into individual recipes.

What you're looking for is #556
