### ISSUE TITLE
Some dropdowns not populated correctly

### ISSUE THREAD

**Issue by DRY411S** [factoriolab/factoriolab#999]
When I reboot my PC and restart Chrome, choose to load a saved state from the dropdown, I see what look like variable names in some dropdowns.

**To Reproduce**
1. Start PC
2. Start Chrome
3. Use factoriolab bookmark
4. Select a saved state and choose 'Load Saved State'
5.  The dropdowns in the Objectives section are filled with what looks like variables names rather than text. (See screenshot)
6. Some of the column headings in the Factory section also contain variable names

**Expected behavior**
Dropdowns with text rather than variable names

**Screenshots**
![image](https://user-images.githubusercontent.com/19732374/218968135-a609a3b4-29c7-4652-a69c-fd26adf9c809.png)
(Note I pulled down the top dropdown to shown that every option is using the variable name)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit Pro
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Additional Information
If I just use 'Skip' after starting factoriolab, the headings are correct, From there, load saved state and aevrything is good.
Shut down factoriolab. Use bookmark again, load saved state, problem reoccurs.

**Comment by dcbroad3** [comment]
That is extremely strange. Does this _only_ occur after a restart of your PC? 
That dropdown was only recently converted to be localized (the text used to be hard coded) so I have to wonder if something is cached on your machine. You could try doing a hard reload of the page (shift + refresh or shift + F5).
I can't seem to reproduce this issue no matter what I do, and I don't see anything in the code that would cause this issue. z

What do the "Items," "Wagons," and "Pollution" column headers in the list view look like when this happens? Those were also updated as part of the same pull request.

**Comment by DRY411S** [comment]
I'll produce some more diagnosis when I get back from my 2.5 week vacation!

**Comment by dcbroad3** [comment]
Enjoy your vacation :)

**Comment by DRY411S** [comment]
> That is extremely strange.
> 
> <snip>You could try doing a hard reload of the page (shift + refresh or shift + F5). I can't seem to reproduce this issue no matter what I do, and I don't see anything in the code that would cause this issue.

If I load chrome, load factoriolab, load the named saved state, I have the issue as I describe it.
If I then hard reload the 'corrupt' page, as you suggest, then it is displayed properly.
If I then close chrome, open chrome, load factoriolab, then load the named saved state, the issue is still there!

FWIW, the name of the saved state is '1K + power + shells' and the URL is https://factoriolab.github.io/list?z=eJxFisEKg0AMRP8mhzklBa0e1WXtUhD.YA6lPaooeNxvd1eFJjDvZcjiPjBVpUtgnZ1uhBXyNYQYWJ5Z5ZS1nQEfPZTdclpeGN109Q.5GTt4pH--bgY0HJKbpqO.y.dF2QA0wDij7fGfSvbnAXkVJ0s_&v=7

> 
> What do the "Items," "Wagons," and "Pollution" column headers in the list view look like when this happens? Those were also updated as part of the same pull request.

![image](https://user-images.githubusercontent.com/19732374/222952099-b8d95109-2d59-439f-a42c-bd719533f949.png)

**Comment by DRY411S** [comment]
FWIW, I have added a new saved state, and the error no longer occurs. Suggest this issue can be closed, and will do so, but your code, so reopen if you wish.

**Comment by dcbroad3** [comment]
Thanks for the info, I want to at least check out your old saved state to see if I can repro this issue. It's entirely possible there is a bug in the migration that is causing issues.

**Comment by dcbroad3** [comment]
Nope, I still can't duplicate this problem with the exact same saved state.
